config/routes.rb
Rails.application.routes.draw do
  root 'react#index'
  #Added v0 prefix to all rails routes
  #Rails routes blocking offline saving if no prefix
  scope :v0 do

    get "/blog" => "blog_posts#index", as: :v0_blog_posts
    post "/blog" => "blog_posts#create", as: :v0_create_blog_post
    get '/blog/search', to: 'blog_posts#search', as: :v0_blog_search
    get '/blog/dashboard', to: 'blog_posts#dashboard', as: :v0_blog_dashboard
    get '/blog/drafts', to: 'blog_posts#drafts', as: :v0_blog_drafts
    get '/blog/scheduled_posts', to: 'blog_posts#scheduled_posts', as: :v0_blog_scheduled_posts
    get '/blog/de_activated', to: 'blog_posts#de_activated', as: :v0_blog_de_activated
    get '/blog/new_comments', to: 'blog_posts#new_comments', as: :v0_new_comments
    resources :blog_posts,  except: [:create, :index] do
      get :autocomplete_tag_name, :on => :collection
      resources :comments, only: [:create, :destroy]
    end

    # devise_for :users
    #devise_for :users, :skip=>[:omniauth_callbacks, :sessions], :controllers => { :registrations => 'registrations'}
    get '/lists/:id/download', to: "api/v1/lists#download", as: :list_download

    resources 'illustrations' do
      get :autocomplete_user_email, :on => :collection
      get :autocomplete_tag_name, :on => :collection
    end

    #Organization_routes
    get '/organizations/organization_sign_up_model', to: 'organizations#organization_sign_up_model', as: :organization_sign_up_model
    post '/organizations/organization_sign_up', to: 'organizations#organization_sign_up', as: :organization_sign_up
    get '/organizations/new_users', to: 'organizations#new_users', as: :new_users
    get '/organizations/organizations_list', to: 'organizations#organizations_list', as: :organizations_list
    get 'organizations/assign_org_role', to: 'organizations#assign_org_role', as: :assign_org_role
    get '/organizations/check_org_publisher', to: 'organizations#check_org_publisher', as: :check_org_publisher
    post '/organizations/add_org_logo', to: 'organizations#add_org_logo', as: :add_org_logo
    #get '/organizations/remove_site_role', to: 'organizations#remove_site_role', as: :remove_site_role
    get '/organizations/validate_org_name_country', to: 'organizations#validate_org_name_country', as: :validate_org_name_country
    get '/organizations/autocomplete', to: 'organizations#autocomplete', as: :organizations_autocomplete
    get 'organizations/remove_org_role_dialog', to: 'organizations#remove_org_role_dialog', as: :remove_org_role_dialog
    get 'organizations/remove_org_role', to: 'organizations#remove_org_role', as: :remove_org_role

    get '/illustrations/:id/new_flag_illustration', to: 'illustrations#new_flag_illustration' , as: :new_flag_illustration
    post '/illustrations/flag_illustration/:id', to: 'illustrations#flag_illustration' , as: :flag_illustration

    get '/illustrations/download/:id', to: 'illustrations#download', as: :download_illustrations
    get '/illustration-view/:id', to: 'illustrations#illustration_view', as: :view_illustration
    post '/illustrations/update_favorites', to: 'illustrations#update_favorites', as: :update_favorites
    post '/illustrations/reset_illustration_download_count', to: 'illustrations#reset_illustration_download_count', as: :reset_illustration_download_count

    resources 'stories',  except: [:show, :index] do
      resources 'pages' do
        get 'epub'
      end
      resources 'translations'
      resources 'relevels'
      member do
        patch 'publish'
      end
      get :autocomplete_tag_name, :on => :collection
    end
    get 'profile/change_translator' => 'profile#change_translator', as: :profile_change_translator

    get "/stories/new_story_from_illustration/:id", to: "stories#new_story_from_illustration", as: :new_story_from_illustration
    get "/stories/create_story_from_illustration", to: "stories#create_story_from_illustration", as: :create_story_from_illustration
    get '/stories/:id/editable', to: 'stories#editable' , as: :story_editor_editable
    post '/stories/reviewer_rating_comment', to: 'stories#reviewer_rating_comment', as: :reviewer_rating_comment
    get '/stories/edit_story_editor/:id', to: 'stories#edit_story_editor', as: :edit_story_editor
    patch '/stories/:id/assign_change_editor', to: 'stories#assign_change_editor', as: :assign_change_editor
    get '/stories/close_assign_dailog/:id', to: 'stories#close_assign_dailog', as: :close_assign_dailog
    post "/stories/recommend_story_on_home", to: "stories#recommend_story_on_home", as: :recommend_story_on_home
    get '/stories/download-story/:id', to: 'stories#download_story', as: :download_story
    post '/stories/reset_story_download_count', to: 'stories#reset_story_download_count', as: :reset_story_download_count

    get 'stories/show-in-iframe/:id', to: 'stories#show_in_iframe', as: :v0_show_story_in_iframe
    get 'stories/:id/story-review', to: 'stories#story_review', as: :story_review
    post 'stories/:id/reviewer-comments', to: "stories#reviewer_comments", as: :reviewer_comments
    get 'stories/review_next_story/:id', to: "stories#review_next_story", as: :review_next_story
    resources 'illustration_crops'

    # editor routes
    patch '/editor/:id/update_dummy_draft', to: "story_editor#update_dummy_draft", as: :update_dummy_draft
    get '/editor/story/user_email', to: 'story_editor#get_email', as: :story_editor_get_email
    get '/editor/story/:id', to: 'story_editor#story' , as: :story_editor
    get '/editor/illustration/:id', to: 'story_editor#illustration_for_crop' , as: :illustration_for_crop, :defaults => { :format => :json }
    post '/editor/:page_id/crop/:id', to: 'story_editor#crop_illustration' , as: :crop_illustration
    get '/editor/page/:id', to: 'story_editor#page_edit' , as: :page_edit
    put '/editor/page/:page_id/change_template/:id', to: 'story_editor#change_page_template' , as: :change_template
    put '/editor/story/:story_id/insert/:id', to: 'story_editor#insert_page' , as: :insert_page
    put '/editor/story/:story_id/duplicate/:id', to: 'story_editor#duplicate_page' , as: :duplicate_page
    delete '/editor/story/:story_id/delete/:id', to: 'story_editor#delete_page' , as: :delete_page
    post '/editor/page/:id/illustration', to: 'story_editor#update_page_illustration', as: :update_page_illustration
    get '/editor/page/:id/illustration', to: 'story_editor#remove_page_illustration', as: :remove_page_illustration
    post '/editor/page/:id/content', to: 'story_editor#update_page_content', as: :update_page_content
    post '/editor/page/:id/auto_save_content', to: 'story_editor#auto_save_content', as: :auto_save_content
    post '/editor/page/:id/save_content_on_blur', to: 'story_editor#save_content_on_blur', as: :save_content_on_blur
    post '/editor/story/:id/rearrange', to: 'story_editor#rearrange_page', as: :rearrange_page
    get '/editor/search/illustration', to: 'story_editor#search_illustration', as: :search_illustration
    get '/editor/new_illustration', to: 'story_editor#new_illustration', as: :editor_new_illustration
    post '/editor/create_illustration', to: 'story_editor#create_illustration', as: :editor_create_illustration
    get '/editor/story/:id/validate_pages', to: 'story_editor#validate_story_pages', as: :editor_validate_story_pages
    get '/editor/story/:id/publish', to: 'story_editor#publish_form', as: :editor_publish_story_form
    get '/editor/story/:id/edit_book_info', to: 'story_editor#edit_book_info', as: :editor_edit_book_info
    patch '/editor/story/:id/publish', to: 'story_editor#publish', as: :editor_publish_story
    patch '/editor/story/:id/update', to: 'story_editor#update', as: :editor_update_story
    patch '/editor/story/:id/update_book_info', to: 'story_editor#update_book_info', as: :editor_update_book_info
    get '/editor/autocomplete_user_email', to: 'story_editor#autocomplete_user_email', as: :autocomplete_user_email_path
    get '/editor/save_to_draft', to: 'story_editor#save_to_draft', as: :save_to_draft
    get '/editor/get-all-illustrations', to: 'story_editor#get_all_illustrations', as: :get_all_illustrations
    get '/editor/get-favourite-illustrations', to: 'story_editor#get_favourite_illustrations', as: :get_favourite_illustrations
    get '/editor/upload-illustration', to: 'story_editor#upload_illustration', as: :upload_illustration
    get '/editor/language_script', to: "story_editor#language_script", as: :story_language_script
    get "/editor/create", to: "stories#create_story", as: :create_story
    get "/editor/:story_id/translate", to: "translations#translate_story", as: :translate_story
    get "/editor/:story_id/relevel", to: "relevels#relevel_story", as: :relevel_story

    # illustration tags
    get '/illustration/edit-tags/:id', to: 'illustrations#edit_tags', as: :edit_illustration_tags
    patch '/illustration/:id/update-tags', to: 'illustrations#update_tags', as: :update_illustration_tags
    get 'illustration/:id/used_stories', to: 'illustrations#illustration_used_in_stories', as: :illustration_used_in_stories
    #contest routes
    get 'contests/:id/contest_winners_details', to: 'contests#contest_winners_details', as: :contest_winners_details
    resources :contests
    get '/contests/:id/details', to: 'contests#contest_details', as: :contest_details
    #contest_illustrations
    post '/illustrations/contest_image', to: 'illustrations#contest_image', as: :contest_image
    get '/contests/:id/submitted_stories', to: 'contests#submitted_stories', as: :contest_submitted_stories
    post '/contests/story_rating_comments', to: 'contests#story_rating_comments', as: :story_rating_comments
    post '/contests/user_update_rating_comments', to: 'contests#user_update_rating_comments', as: :user_update_rating_comments
    post '/contests/user_update_rating_without_comments', to: 'contests#user_update_rating_without_comments', as: :user_update_rating_without_comments

app/controllers/api/v1/dashboard_controller.rb
class Api::V1::DashboardController < Api::V1::ApplicationController

  respond_to :json
  before_action :authenticate_user!
  before_action :authorize_action

  def institutional_users
    institutional_users = InstitutionalUser.all.reorder("created_at DESC").page(params[:page]).per(12)
    render json: institutional_users
  end

  private
  def authorize_action
    authorize self, :default
  end

end

app/views/dashboard/_languages_added.html.erb
<%= render :partial => "dashboard_datatables" %>
<h2>Languages Added Monthwise</h2>
<table class="table table-striped" id="languages_added_by_month">
  <tfoot style="display: table-header-group;">
    <tr>
      <th>Month</th>
      <th>No. of languages added</th>
      <th>Present no. of languages</th>
      <th>Languages added</th>
    </tr>
  </tfoot>
  <thead>
    <tr class="table-heading-row">
      <th width='150px'>Month</th>
      <th>No. of languages added</th>
      <th>Present no. of languages</th>
      <th>Language added</th>
    </tr>
  </thead>
  <tbody class="table-row-details">
    <% total_count = 0 %>
    <% languages_added.each do |k, v| %>
      <% total_count = total_count + v.count %>
      <tr>
        <td><%= k.strftime("%B-%Y")  %></td>
        <td><%= v.count  %></td>
        <td><%= total_count  %></td>
        <td><%=v.map(&:name).join(', ') %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<script type="text/javascript">
$(document).ready(function() {
  var table = $('#languages_added_by_month').DataTable( {
    searching: true,
    lengthChange: false,
    showNEntries: false,
    pageLength: 10,
    order: [],
    responsive: {
        details: false
    },
    dom: '<"col-md-6 col-sm-6"B><"col-md-6 col-sm-6"f><"col-md-12 col-sm-12"p>rti',
    buttons: [
              {
                  extend: 'copyHtml5',
                  title: formatDatatableTitle('languages'),
                  exportOptions: {
                      columns: [ 0, 1, 2, 3 ]
                  }
              },
              {
                  extend: 'csvHtml5',
                  title: formatDatatableTitle('languages'),
                  exportOptions: {
                      columns: [ 0, 1, 2, 3 ]
                  }
              },
              {
                  extend: 'excelHtml5',
                  title: formatDatatableTitle('languages'),
                  exportOptions: {
                      columns: [ 0, 1, 2, 3 ]
                  }
              },
              {
                  extend: 'pdfHtml5',
                  title: formatDatatableTitle('languages'),
                  exportOptions: {
                      columns: [ 0, 1, 2, 3 ]
                  }
              }
          ]
      
  });

  var new_table = $('#languages_added_by_month').dataTable();

  $('#languages_added_by_month tfoot th').each( function () {
      var title = $(this).text();
      $(this).html( '<input type="text" placeholder="Search '+title+'" />' );
  });

  table.columns().every( function () {
      var that = this;

      $( 'input', this.footer() ).on( 'keyup change', function () {
          if ( that.search() !== this.value ) {
              that
                  .search( this.value )
                  .draw();
          }
      });
  });

  });
</script>

app/views/dashboard/_levelwise_downloaded_stories.html.erb
<%= render :partial => "dashboard_datatables" %>
<h2>Level wise Total number of downloads</h2>
<table class="table table-striped" id="levelwise_downloaded_stories">
  <thead>
    <tr class="table-heading-row">
      <th>Level</th>
      <th>TOTAL number of downloads</th>
    </tr>
  </thead>
  <tbody class="table-row-details">
    <% @levelwise_download_count.each do |key,value| %>
      <tr>
        <td><%= key %></td>
        <td><%= value %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<script type="text/javascript">
$(document).ready(function() {
  var table = $('#levelwise_downloaded_stories').DataTable( {
    searching: false,
    paging: false,
    lengthChange: false,
    showNEntries: false,
    pageLength: 10,
    order: [],
    responsive: {
        details: false
    },
    dom: '<"col-md-6 col-sm-6"B><"col-md-6 col-sm-6"f><"col-md-12 col-sm-12"p>rti',
    buttons: [
              {
                  extend: 'copyHtml5',
                  title: formatDatatableTitle('levelwise-stories'),
                  exportOptions: {
                      columns: [ 0, 1 ]
                  }
              },
              {
                  extend: 'csvHtml5',
                  title: formatDatatableTitle('levelwise-stories'),
                  exportOptions: {
                      columns: [ 0, 1 ]
                  }
              },
              {
                  extend: 'excelHtml5',
                  title: formatDatatableTitle('levelwise-stories'),
                  exportOptions: {
                      columns: [ 0, 1 ]
                  }
              },
              {
                  extend: 'pdfHtml5',
                  title: formatDatatableTitle('levelwise-stories'),
                  exportOptions: {
                      columns: [ 0, 1 ]
                  }
              }
          ]
      
  });

  var new_table = $('#levelwise_downloaded_stories').dataTable();

  });
</script>

app/views/dashboard/_most_used_illustrations.html.erb
<div class="btn-group">
  <i class="dropdown-arrow dropdown-arrow-inverse"></i>
  <button class="btn btn-primary limit dropdown-toggle filter-btn" data-toggle="dropdown" >Top <%= params[:limit] ? params[:limit] : 10 %></button>
  <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> <span class="caret"></span>
  </button>
  <ul class="dropdown-menu dropdown-limit">
    <% [10, 20, 30, 40, 50, 100].each do |limit| %>
     <li><%= link_to "Top #{limit}", most_used_illustrations_path(:limit => limit, :organization=>params[:organization]? params[:organization] : ''), :remote => true%></li>
    <% end %>
  </ul>
</div>
<div class="btn-group">
  <i class="dropdown-arrow dropdown-arrow-inverse"></i>
  <button class="btn btn-primary levels dropdown-toggle filter-btn" data-toggle="dropdown" ><%= params[:organization] && params[:organization] != ''? params[:organization] : "All organizations" %></button>
  <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> <span class="caret"></span>
  </button>
  <ul class="dropdown-menu dropdown-levels">
    <li><%= link_to "All Organizations", most_used_illustrations_path(:organization => "", :limit => params[:limit]? params[:limit] : 10), :remote => true%></li>
    <% @organizations.each do |organization| %>
     <li><%= link_to organization.organization_name, most_used_illustrations_path(:organization => organization.organization_name, :limit => params[:limit]? params[:limit] : 10), :remote => true%></li>
    <% end %>
    <li><%= link_to "Community", most_used_illustrations_path(:organization => "community", :limit => params[:limit]? params[:limit] : 10), :remote => true%></li>
  </ul>
</div>
<table class="table table-striped">
  <thead>
  <tr class="table-heading-row">
    <th>Illustration Title</th>
    <th>Organization</th>
    <th>No of places</th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody class="table-row-details">
  <% if illustrations %>
   <% illustrations.each do |illustration| %>
    <tr>
      <td><%= link_to illustration.name, illustration_path(illustration) %></td>
      <td><%= illustration.organization.present? ? illustration.organization.organization_name : 'Storyweaver Community' %></td>
      <td><%= illustration.story_count%></td>
      <td>
      </td>
      <td></td>
    </tr>
   <% end %>
  <% end %>
  </tbody>
</table>

app/views/dashboard/_recently_published_stories.html.erb
<%= render :partial => "dashboard_datatables" %>

<div class="btn-group">
  <span><%= t 'dashboard.number_of_stories_selected'%> :</span>
  <span class="badge" id="all_published_stories_count"><%= stories.count %></span>
</div>

<table class="table table-striped" id="all_published_stories">
  <tfoot style="display: table-header-group;">
    <tr>
      <th><%= t 'dashboard.story_title'%></th>
      <th><%= t 'dashboard.english_title'%></th>
      <th><%= t 'dashboard.author'%></th>
      <th><%= t 'dashboard.language'%></th>
    </tr>
  </tfoot>
  <thead>
    <tr class="table-heading-row">
      <th><%= t 'dashboard.story_title'%></th>
      <th><%= t 'dashboard.english_title'%></th>
      <th><%= t 'dashboard.author'%></th>
      <th class="noborder"><%= t 'dashboard.language'%></th>
    </tr>
  </thead>
  <tbody class="table-row-details">
    <% stories.each do |story| %>
      <tr class="published_stories_count">
        <td class="<%=story.language.script %> underline-class"><%= link_to story.title, react_stories_show_path(story.to_param) , :target => "_blank" %></td>
        <td><%= story.english_title %></td>
        <td><%= story.authors.collect(&:name).join(",")%></td>
        <td><%= story.language.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<script type="text/javascript">

$(document).ready(function() {
  var table = $('#all_published_stories').DataTable( {
    searching: true,
    lengthChange: false,
    showNEntries: false,
    pageLength: 20,
    order: [],
    responsive: {
        details: false
    },
    dom: '<"col-md-6 col-sm-6"B><"col-md-6 col-sm-6"f><"col-md-12 col-sm-12"p>rti',
    buttons: [
              {
                  extend: 'copyHtml5',
                  title: formatDatatableTitle('recently-published-stories'),
                  exportOptions: {
                      columns: [ 0, 1, 2, 3 ]
                  }
              },
              {
                  extend: 'csvHtml5',
                  title: formatDatatableTitle('recently-published-stories'),
                  exportOptions: {
                      columns: [ 0, 1, 2, 3 ]
                  }
              },
              {
                  extend: 'excelHtml5',
                  title: formatDatatableTitle('recently-published-stories'),
                  exportOptions: {
                      columns: [ 0, 1, 2, 3 ]
                  }
              },
              {
                  extend: 'pdfHtml5',
                  title: formatDatatableTitle('recently-published-stories'),
                  exportOptions: {
                      columns: [ 0, 1, 2, 3 ]
                  }
              }
          ]
      
  });
  $('#all_published_stories tfoot th').each( function () {
      var title = $(this).text();
      $(this).html( '<input type="text" placeholder="Search '+title+'" />' );
  });

  var new_table = $('#all_published_stories').dataTable();
  table.columns().every( function () {
    var that = this;

    $( 'input', this.footer() ).on( 'keyup change', function () {
      if ( that.search() !== this.value ) {
          that
              .search( this.value )
              .draw();
        document.getElementById("all_published_stories_count").innerHTML = document.getElementById('all_published_stories').children[1].childElementCount;
      }else{
        document.getElementById("all_published_stories_count").innerHTML = table.rows( '.published_stories_count' ).count(); 
      }
    });
  });
  $( 'input').on( 'keyup change', function () {
    document.getElementById("all_published_stories_count").innerHTML = new_table.fnSettings().fnRecordsDisplay();
  });

  });
</script>

app/views/dashboard/_translator_tabs.html.erb
<div class="row full-content-dash prof-act">
  <div class="col-md-12">
    <ul id="myTab" role="tablist" class="nav nav-tabs profile">
       <li role="presentation" class="<%= @current_tab == 'un_translated_stories' ? 'active' : '' %>">
        <%= link_to "<span>Stories to Translate</span>".html_safe , un_translated_stories_path %>
      </li>
      <li role="presentation" class="<%= @current_tab == 'translated_stories' ? 'active' : '' %>">
        <%= link_to "<span>Translated Stories</span>".html_safe , translated_stories_path %>
      </li>
      <li role="presentation" class="<%= @current_tab == 'translation_drafts' ? 'active' : '' %>">
        <%= link_to "<span>Translation Drafts</span>".html_safe , translation_drafts_path %>
      </li>
      <li role="presentation" class="<%= @current_tab == 'assign_translator' ? 'active' : '' %>">
        <%= link_to "<span>Translators</span>".html_safe , assign_translator_path %>
      </li>
      <li role="presentation" class="<%= @current_tab == 'translator_analytics' ? 'active' : '' %>">
        <%= link_to "<span>Analytics</span>".html_safe , translator_analytics_path %>
      </li>
    </ul>
  </div>
  <hr>
</div>

app/views/dashboard/all_stories.js.erb
$("#uniqe_test").html("<%= escape_javascript(render :partial=> "all_stories") %>");

app/views/dashboard/delete_language_translator_dialog.js.erb
$("#delete_translator_dialog").html("<%= escape_javascript(render :partial=> "delete_language_translator_dialog", :locals => {:language => @language, :translator => @user}) %>");

app/views/dashboard/illustration_categories.html.erb
<%= render :partial => "errors" %>

<%= render :partial => "tabs" %>

<div class="tab-content">

  <div role="tabpanel" class="tab-pane active common-class" id="Categories">
    <%= render :partial => "illustration_categories" %>
  </div>

</div>

app/views/dashboard/index.html.erb
<%= render :partial => "errors" %>

<%= render :partial => "tabs" %>

<div class="tab-content">
  <div role="tabpanel" class="tab-pane active common-class" id="LegacyUpload">
      <%= render :partial => "upload" %>
  </div>
</div>

app/views/dashboard/languages.html.erb
<% if flash[:errors].try(:any?) %>
  <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <% flash[:errors].each do |key,value| %>
      <div id="flash_error"><%= "#{key.titleize}: #{value.is_a?(Array) ? value.join(",") : value }" %></div>
      <% end %>
  </div>
<% end %>


<%= render :partial => "tabs" %>

<div class="tab-content">
  <div role="tabpanel" class="tab-pane active common-class" id="LegacyUpload">
      <%= render :partial => "languages" %>
  </div>
</div>

app/views/dashboard/lists.html.erb
<%= render :partial => "dashboard/dashboard_datatables" %>
<%= render :partial => "tabs" %>

<div class="btn-group">
  <span><%=t 'dashboard.lists_tab.number_of_lists_selected'%> :</span>
  <span class="badge" id="all_lists_count"><%= @lists.count %></span>
</div>

<table class="table table-striped" id="all_lists">
  <tfoot style="display: table-header-group;">
    <tr>
      <th><%=t 'dashboard.lists_tab.id'%></th>
      <th><%=t 'dashboard.lists_tab.name'%></th>
      <th><%=t 'dashboard.organization'%></th>
      <th><%=t 'dashboard.lists_tab.creator'%></th>
      <th><%=t 'dashboard.lists_tab.status'%></th>
    </tr>
  </tfoot>
  <thead>
    <tr class="table-heading-row">
      <th><%=t 'dashboard.lists_tab.id'%></th>
      <th><%=t 'dashboard.lists_tab.name'%></th>
      <th><%=t 'dashboard.organization'%></th>
      <th><%=t 'dashboard.lists_tab.creator'%></th>
      <th><%=t 'dashboard.lists_tab.status'%></th>
    </tr>
  </thead>
  <tbody>
    <% @lists.each do |f|%>
      <tr class="lists_count">
        <td><%= f.id %></td>
        <td><%= f.title %></td>
        <td><%= f.user.organization.organization_name %></td>
        <td><%= f.user.name %></td>
        <td><%= link_to (f.status=="published") ? "Unpublish" : "Publish", update_lists_path(:id => f.id), class: f.organization_id.present? ? "btn btn-danger" : "btn btn-success" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<script type="text/javascript">

$(document).ready(function() {
  var table = $('#all_lists').DataTable( {
    searching: true,
    lengthChange: false,
    showNEntries: false,
    pageLength: 20,
    order: [],
    responsive: {
        details: false
    },
    dom: '<"col-md-6 col-sm-6"B><"col-md-6 col-sm-6"f><"col-md-12 col-sm-12"p>rti',
    buttons: [
              {
                  extend: 'copyHtml5',
                  title: formatDatatableTitle('lists'),
                  exportOptions: {
                      columns: [ 0, 1, 2, 3, 4 ]
                  }
              },
              {
                  extend: 'csvHtml5',
                  title: formatDatatableTitle('lists'),
                  exportOptions: {
                      columns: [ 0, 1, 2, 3, 4 ]
                  }
              },
              {
                  extend: 'excelHtml5',
                  title: formatDatatableTitle('lists'),
                  exportOptions: {
                      columns: [ 0, 1, 2, 3, 4 ]
                  }
              },
              {
                  extend: 'pdfHtml5',
                  title: formatDatatableTitle('lists'),
                  exportOptions: {
                      columns: [ 0, 1, 2, 3, 4 ]
                  }
              }
          ]
      
  });
  $('#all_lists tfoot th').each( function () {
      var title = $(this).text();
      $(this).html( '<input type="text" placeholder="Search '+title+'" />' );
  });

  var new_table = $('#all_lists').dataTable();
  table.columns().every( function () {
    var that = this;

    $( 'input', this.footer() ).on( 'keyup change', function () {
      if ( that.search() !== this.value ) {
          that
              .search( this.value )
              .draw();
        document.getElementById("all_lists_count").innerHTML = document.getElementById('all_lists').children[1].childElementCount;
      }else{
        document.getElementById("all_lists_count").innerHTML = table.rows( '.lists_count' ).count(); 
      }
    });
  });
  $( 'input').on( 'keyup change', function () {
    document.getElementById("all_lists_count").innerHTML = new_table.fnSettings().fnRecordsDisplay();
  });

  });
</script>

app/views/dashboard/most_downloaded_stories.js.erb
$("#stories-list").html("<%= escape_javascript(render :partial => "most_downloaded_stories", :locals => {:stories => @downloads_by_filter, :reads => false}) %>");
$('#tabs a').click(function (e) {
  e.preventDefault()
  $(this).tab('show')
})

app/views/dashboard/recently_published.html.erb
<%= render :partial => "errors" %>

<%= render :partial => "tabs" %>

<div class="tab-content">
  <div role="tabpanel" class="tab-pane active common-class" id="LegacyUpload">
    <%= render :partial => "recently_published_stories" ,:locals => {:stories => @stories}%>
  </div>
</div>

app/views/dashboard/story_dwonload_analytics.js.erb
$("#illustrations-list").html("<%= escape_javascript(render :partial => "organization_summery", :locals => {:story_downloads => @story_downloads, :stories_download_count => @stories_download_count}) %>");