config/routes.rb
    get '/editor/page/:id', to: 'story_editor#page_edit' , as: :page_edit
    put '/editor/page/:page_id/change_template/:id', to: 'story_editor#change_page_template' , as: :change_template
    put '/editor/story/:story_id/insert/:id', to: 'story_editor#insert_page' , as: :insert_page
    put '/editor/story/:story_id/duplicate/:id', to: 'story_editor#duplicate_page' , as: :duplicate_page
    delete '/editor/story/:story_id/delete/:id', to: 'story_editor#delete_page' , as: :delete_page
    post '/editor/page/:id/illustration', to: 'story_editor#update_page_illustration', as: :update_page_illustration
    get '/editor/page/:id/illustration', to: 'story_editor#remove_page_illustration', as: :remove_page_illustration
    post '/editor/page/:id/content', to: 'story_editor#update_page_content', as: :update_page_content
    post '/editor/page/:id/auto_save_content', to: 'story_editor#auto_save_content', as: :auto_save_content
    post '/editor/page/:id/save_content_on_blur', to: 'story_editor#save_content_on_blur', as: :save_content_on_blur
    post '/editor/story/:id/rearrange', to: 'story_editor#rearrange_page', as: :rearrange_page
    get '/editor/search/illustration', to: 'story_editor#search_illustration', as: :search_illustration
    get '/editor/new_illustration', to: 'story_editor#new_illustration', as: :editor_new_illustration
    post '/editor/create_illustration', to: 'story_editor#create_illustration', as: :editor_create_illustration
    get '/editor/story/:id/validate_pages', to: 'story_editor#validate_story_pages', as: :editor_validate_story_pages
    get '/editor/story/:id/publish', to: 'story_editor#publish_form', as: :editor_publish_story_form
    get '/editor/story/:id/edit_book_info', to: 'story_editor#edit_book_info', as: :editor_edit_book_info
    patch '/editor/story/:id/publish', to: 'story_editor#publish', as: :editor_publish_story
    patch '/editor/story/:id/update', to: 'story_editor#update', as: :editor_update_story
    patch '/editor/story/:id/update_book_info', to: 'story_editor#update_book_info', as: :editor_update_book_info
    get '/editor/autocomplete_user_email', to: 'story_editor#autocomplete_user_email', as: :autocomplete_user_email_path
    get '/editor/save_to_draft', to: 'story_editor#save_to_draft', as: :save_to_draft
    get '/editor/get-all-illustrations', to: 'story_editor#get_all_illustrations', as: :get_all_illustrations
    get '/editor/get-favourite-illustrations', to: 'story_editor#get_favourite_illustrations', as: :get_favourite_illustrations
    get '/editor/upload-illustration', to: 'story_editor#upload_illustration', as: :upload_illustration
    get '/editor/language_script', to: "story_editor#language_script", as: :story_language_script
    get "/editor/create", to: "stories#create_story", as: :create_story
    get "/editor/:story_id/translate", to: "translations#translate_story", as: :translate_story
    get "/editor/:story_id/relevel", to: "relevels#relevel_story", as: :relevel_story

    # illustration tags
    get '/illustration/edit-tags/:id', to: 'illustrations#edit_tags', as: :edit_illustration_tags
    patch '/illustration/:id/update-tags', to: 'illustrations#update_tags', as: :update_illustration_tags
    get 'illustration/:id/used_stories', to: 'illustrations#illustration_used_in_stories', as: :illustration_used_in_stories
    #contest routes
    get 'contests/:id/contest_winners_details', to: 'contests#contest_winners_details', as: :contest_winners_details
    resources :contests
    get '/contests/:id/details', to: 'contests#contest_details', as: :contest_details
    #contest_illustrations
    post '/illustrations/contest_image', to: 'illustrations#contest_image', as: :contest_image
    get '/contests/:id/submitted_stories', to: 'contests#submitted_stories', as: :contest_submitted_stories
    post '/contests/story_rating_comments', to: 'contests#story_rating_comments', as: :story_rating_comments
    post '/contests/user_update_rating_comments', to: 'contests#user_update_rating_comments', as: :user_update_rating_comments
    post '/contests/user_update_rating_without_comments', to: 'contests#user_update_rating_without_comments', as: :user_update_rating_without_comments
    get 'contests/:id/contest_draft_stories', to: 'contests#contest_draft_stories', as: :contest_draft_stories
    get 'contests/:id/illustration_contest_form', to: 'contests#illustration_form', as: :illustration_contest_form
    post 'contests/:id/create_illustration', to: 'contests#create_illustration', as: :create_illustration
    post '/contests/validate_illustration_name', to: 'contests#validate_illustration_name', as: :validate_illustration_name

    # dashboard routes
    get '/dashboard', to: 'dashboard#index'
    post '/dashboard/upload', to: 'dashboard#upload' , as: :upload
    get '/dashboard/images_upload_new', to: 'dashboard#images_upload_new' , as: :images_upload_new
    post '/dashboard/images_upload', to: 'dashboard#images_upload' , as: :images_upload
    get '/dashboard/roles', to: 'dashboard#roles', as: :roles
    get '/dashboard/remove_site_role_dialog', to: 'dashboard#remove_site_role_dialog', as: :remove_site_role_dialog
    get '/dashboard/remove_site_role', to: 'dashboard#remove_site_role', as: :remove_site_role
    post '/dashboard/set_role', to: 'dashboard#set_role', as: :set_role
    get '/dashboard/autocomplete', to: 'dashboard#autocomplete', as: :users_autocomplete
    get '/dashboard/autocomplete_user_email', to: 'dashboard#autocomplete_user_email', as: :autocomplete_user_email_dashboard

    # story categories
    get '/dashboard/story_categories', to: 'dashboard#story_categories', as: :story_categories
    post '/dashboard/story_category/edit/:id', to: 'dashboard#edit_story_category', as: :edit_story_category
    post '/dashboard/story_category/create', to: 'dashboard#create_story_category', as: :create_story_category

    # illustration categories
    get '/dashboard/illustration_categories', to: 'dashboard#illustration_categories', as: :illustration_categories
    post '/dashboard/illustration_category/edit/:id', to: 'dashboard#edit_illustration_category', as: :edit_illustration_category
    post '/dashboard/illustration_category/create', to: 'dashboard#create_illustration_category', as: :create_illustration_category

    # languages
    get '/dashboard/languages', to: 'dashboard#languages', as: :languages
    post '/dashboard/languages/create', to: 'dashboard#create_language', as: :create_language

    # styles
    get '/dashboard/styles', to: 'dashboard#styles', as: :styles
    post '/dashboard/styles/edit/:id', to: 'dashboard#edit_style', as: :edit_style
    post '/dashboard/styles/create', to: 'dashboard#create_style', as: :create_style

    #assign reviewer to uploaded stories
    post  '/dashboard/assign_editor_to_uploaded_story', to: 'dashboard#assign_editor_to_uploaded_story', as: :assign_editor_to_uploaded_story
    get 'dashboard/assign_editor_modal', to: 'dashboard#assign_editor_modal', as: :assign_editor_modal
    get 'dashboard/delete_editor_modal', to: 'dashboard#delete_editor_modal', as: :delete_editor_modal
    delete 'dashboard/delete_story_reviewer', to: 'dashboard#delete_story_reviewer', as: :delete_story_reviewer
    # flagged stories
    get '/dashboard/flagged_stories', to: 'dashboard#flagged_stories', as: :flagged_stories
    get '/dashboard/analytics', to: 'dashboard#analytics', as: :analytics
    get '/dashboard/most-read-stories', to: 'dashboard#most_read_stories', as: :most_read_stories
    get '/dashboard/most-viewed-illustrations', to: 'dashboard#most_viewed_illustrations', as: :most_viewed_illustrations
    get '/dashboard/most-used-illustrations', to: 'dashboard#most_used_illustrations', as: :most_used_illustrations
    get '/dashboard/most-downloaded-stories', to: 'dashboard#most_downloaded_stories', as: :most_downloaded_stories
    get '/dashboard/most-downloaded-illustrations', to: 'dashboard#most_downloaded_illustrations', as: :most_downloaded_illustrations
    get '/dashboard/flagged_illustrations', to: 'dashboard#flagged_illustrations', as: :flagged_illustrations
    get 'dashboard/all_stories', to: 'dashboard#all_stories', as: :all_stories
    get 'dashboard/lists', to: 'dashboard#lists', as: :lists
    get 'dashboard/update_lists', to: 'dashboard#update_lists', as: :update_lists
    get 'dashboard/all_illustrations', to: 'dashboard#all_illustrations', as: :all_illustrations
    get 'dashboard/organization_downloads', to: 'dashboard#organization_downloads', as: :organization_downloads
    get 'dashboard/organization_user/:id', to: 'dashboard#organization_user', as: :organization_user
    get 'dashboard/organization_users', to: 'dashboard#organization_users', as: :organization_users
    get '/dashboard/pull_down_story/:id', to: 'dashboard#pull_down_story', as: :pull_down_story
    get '/dashboard/clear_story_flag/:id', to: 'dashboard#clear_story_flag', as: :clear_story_flag
    get 'dashboard/stories_downloaded_list', to: 'dashboard#stories_downloaded_list', as: :stories_downloaded_list
    get 'dashboard/story_downloads_date_sort', to: 'dashboard#story_downloads_date_sort', as: :story_downloads_date_sort
    get 'dashboard/story_bulk_downloads', to: 'dashboard#story_bulk_downloads', as: :story_bulk_downloads
    get '/dashboard/languagewise_read_stories', to: 'dashboard#languagewise_read_stories', as: :languagewise_read_stories
    get '/dashboard/languages_added', to: 'dashboard#languages_added', as: :languages_added
    #pulled down stories
    get '/dashboard/pulled_down_stories', to: 'dashboard#pulled_down_stories', as: :pulled_down_stories
    get '/dashboard/pulled_down_illustrations', to: 'dashboard#pulled_down_illustrations', as: :pulled_down_illustrations

    # activate story
    get '/dashboard/activate_story/:id', to: 'dashboard#activate_story', as: :activate_story
    get '/dashboard/activate_illustration/:id', to: 'dashboard#activate_illustration', as: :activate_illustration

    # illustration

app/models/contest.rb
# == Schema Information
#
# Table name: contests
#
#  id                  :integer          not null, primary key
#  name                :string(255)
#  start_date          :datetime
#  end_date            :datetime
#  contest_type        :string(255)
#  created_at          :datetime
#  updated_at          :datetime
#  is_campaign         :boolean          default(FALSE)
#  tag_name            :string(255)
#  custom_flash_notice :string(255)
#

class Contest < ActiveRecord::Base
  include Shared
  acts_as_taggable
	validates :name, presence: true
	validates :contest_type, presence: true
  #validates :languages, presence: true
	validates :start_date, presence: true
	validates :end_date, presence: true
	validates :tag_name, presence: true

	has_many :stories
	has_and_belongs_to_many :languages
	has_and_belongs_to_many :illustrations
  has_one :story_category
  has_many :winners
  accepts_nested_attributes_for :story_category, reject_if: proc { |attrs| attrs[:name].blank? }
  def to_param
    url_slug(id, name.parameterize)
  end

  def contest_languages
  	languages.collect(&:name).join(',')
  end

  def is_running?

  	today_date = DateTime.now.strftime("%Y-%m-%d")
  	if today_date >= self.start_date.strftime("%Y-%m-%d") && today_date <= self.end_date.strftime("%Y-%m-%d")
  		return true
  	else
  		return false
  	end
  end
end

app/views/contests/_contest_details.html.erb
<%= render :partial => "dashboard/errors" %>
<section id="search-details-temp" class="search_google_temp">
  <div class="row">
    <div class="col-md-4 col-sm-12">
      <h2><label><%= @contest.is_campaign? ? "Campaign" : "Contest" %></label></h2>
      <b>Name:</b> <%= @contest.name %></br>
      <b>Type:</b> <%= @contest.contest_type %></br>
      <b>Tag Name:</b> <%= @contest.tag_name.present? ? @contest.tag_name : "nil" %></br>
      <b>Start date:</b> <%= @contest.start_date.localtime.strftime("%d-%m-%y") %></br>
      <b>End date:</b> <%= @contest.end_date.localtime.strftime("%d-%m-%y") %></br>
      <% unless @contest.contest_type == "illustration" %>
        <b>Languages:</b> <%= @contest.contest_languages %></br>
        <b>Category:</b> <%= @contest.story_category.name if @contest.story_category.present? %></br>
      <% end %>
      <b>Custom Flash Message:</b> <%= @contest.custom_flash_notice %></br>
      </div>
      <div class="upload-illustr contest_details_button">
        <a class="btn btn-primary btn-lg" href = "<%= edit_contest_path(@contest.id) %>"style="margin-right: 10px ! important;">Update Details</a>
        <%# unless @contest.contest_type == "illustration" #RRR 2016%> 
          <!-- <a href="<%#= illustrations_path(:contest_id => @contest.id) %>" class="btn btn-primary btn-lg" target="_blank">Add Image</a> -->
        <%# end %>
    </div>
  </div>
</section>

app/views/contests/_illustration_form.html.erb
<script>
  $(document).ready(function(){
    var main_image_name_exist = false;
    var key_image_name_exist = false;
  })
</script>
<div class="modal fade" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="moreLinksModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <%= simple_nested_form_for @illustration, :url => create_illustration_path, html: { :onsubmit=> "return validateForm()", class: 'form-horizontal',  multipart: true, novalidate: false, method: :post }, :authenticity_token => true do |f| %>
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close mypopup-close upload-close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"><i class="fa fa-times"></i> Close</span>
          </button>
          <h2 class="modal-title">Uploading images for Spotathon</h2>
          <div class="tip">
            <h5>Hi, uploading an image for the first time?</h5>
            Thank you for uploading your image on StoryWeaver. Please upload your ORIGINAL work here and have a look at the  <a href="/uploading_an_illustration#faq2" target="_blank">good practices</a> to follow. Please ensure that your image is at least 150 dpi. By accepting our <a href="/terms_and_conditions" target="_blank">Terms &amp; Conditions </a> you are agreeing to your work being licensed under CC-BY 4.0 license and used by other users.
          </div>
          <% if @illustration.errors.count != 0 %>
            <div class="alert alert-danger">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
               <div id="flash_error"><%= @illustration.errors.full_messages.join(", ") %></div>
            </div>
          <% end %>
          <% if @illustration1.errors.count != 0 %>
            <div class="alert alert-danger">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <div id="flash_error"><%= @illustration1.errors.full_messages.join(", ") %></div>
            </div>
          <% end %>
          <div class="row">
            <div class="col-md-4 padding-left" style="margin-left: 25px; margin-top: 10px"><label>Main image</label></div>
            <div class="upload-full-browse1-illustration-contest">
              <input id="uploadFile1" placeholder="Upload only jpeg or png images" disabled="disabled" required/>
              <div class="fileUpload btn btn-primary">
                <span>Browse</span>
                <input id="uploadBtn1" type="file" class="upload" name="illustration[image]" value="" required />
              </div>
              <div style= "margin-top: 10px">
                <%= f.input :name,label: "Image name", title: 'Name your image in a way that makes it easy for a user to find it', icon: "fa fa-info-circle info", input_html: { required: true, class: "spotathon_form", :onchange => "check_image_name_exist($(this).val(), 'main_image');"},:error => false, label_html: {:style => "padding-bottom: 7px;"} %>
              </div>
            </div>

            <div style="margin-left: 25px; padding-top: 7px;"><label>Answer key</label></div>
            <div class="upload-full-browse2-illustration-contest">
              <input id="uploadFile2" placeholder="Upload only jpeg or png images" disabled="disabled" />
              <div class="fileUpload btn btn-primary">
                <span>Browse</span>
                <input id="uploadBtn2" type="file" class="upload" name="image" required/>
              </div>
              <div style="margin-top: 10px">
                <div class="control-group string required illustration_name">
                  <label class="string required control-label" for="illustration_name" style="padding-bottom: 7px;">
                    <abbr title="required">*</abbr> Image name
                  </label>
                  <i class="fa fa-info-circle info" data-toggle="tooltip" title="" data-original-title="Use the image name used for 'Main image' and add 'answer key' to it. Example: Forest answer key, Kitchen answer key, etc."></i>
                  <div class="controls">
                    <input type="text" class="string required form-control spotathon_form" id="answer_key" name="answer_key_name" value="<%= @illustration1.name %>"  required , onchange = "check_image_name_exist($(this).val(), 'key_image');" />
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-body">
            <div class="row">
              <div class="col-md-12">
                <div class="col-md-4 padding-left"  style= "width: 50%">
                  <%= f.association :categories, multiple: true,label: "Image category",title: 'Choosing a relevant category will help users find the image easily. You can select more than one category for the image', icon: "fa fa-info-circle info", input_html: {required: true}%>
                </div>
                <div class="col-md-4 padding-right"  style= "width: 50%">
                  <%= f.association :styles, multiple: true,label: "Image style",title: 'Tagging the image with a style will help users find relevant images. You can tag the image with more than one image style', icon: "fa fa-info-circle info", input_html: {required: true} %>
                </div>
                <div class="col-md-12 nopadding">
                  <%= f.input :tag_list, title: 'Tags are how you organize images so its easy for other users to find your image and weave a story around it.', icon: "fa fa-info-circle info", class: "spotathon_form", label: "Image tags", url: autocomplete_tag_name_illustrations_path, as: :autocomplete %>
                </div>
                <div class="col-md-4 padding-left btn-group" style= "width: 50%">
                  <%= select_tag :language, options_for_select(Language.all.collect {|p| [ p.name, p.id ] }, @story.language.present? ? Language.find(@story.language_id).id : ""),prompt: "Select language",class: "form-control spotathon_form", required: true %>
                </div>
                <div class="col-md-4 padding-right" style= "width: 50%">
                  <%= select_tag :reading_level, options_for_select([['Easy', '1'],['Medium', '2']], @story.reading_level),prompt: "Level of difficulty",class: "form-control spotathon_form", required: true %>
                </div>
                <div><input type="hidden" name="contest_id" value ="<%= @contest.id %>"></div>
                <div class="col-md-12 nopadding tnc">
                  <input type="checkbox" name="accepts_tnc" id="tnc_checkbox"> I accept the <a href="https://storyweaver.org.in/terms_and_conditions">Terms of Use.</a></input>
                </div>
                <div class="center-btn text-center">
                  <%= f.submit "Upload & start weaving!", class: "btn btn-lg disabled illustrator-up" , id: "sub_illustration",	 :onclick => "javascript:window.onbeforeunload = null;"%>
                  <button class="illustrator-cancel" value="Cancel Upload" data-dismiss="modal">Cancel upload</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <div class="modal fade" id="confirm_form">
      <div class="modal-dialog"> <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Confirmation Required</h4>
          </div>
          <div class="modal-body">
            <p>Is this an ORIGINAL image created by you? Upload this image only if your answer is yes!</p>
            <p>On StoryWeaver, we only allow upload of original images. By accepting our Terms & Conditions, you are agreeing to your work being licensed under a CC-BY 4.0 license. This is a liberal license that allows users to distribute, remix, tweak, and build upon your work, even commercially, as long as they credit you for the original creation. You can read more about this license <a href="http://creativecommons.org/licenses/by/4.0/" target="_blank">here.</a></p>
          </div>
          <div class="modal-footer">
            <button type="button" class="illustrator-cancel" id="confirm" class="btn btn-default">Confirm</button>
            <button type="button" class="illustrator-cancel" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
    <script type="text/javascript">
      $(document).ready(function() {
        $('[data-toggle="tooltip"]').tooltip();

        $('#illustration_style_ids').multiselect({
          buttonWidth : '100%',
          selectedList: 1,
          buttonClass: 'spotathon_form'
        });
        $('#illustration_category_ids').multiselect({
          buttonWidth : '100%',
          selectedList: 1,
          buttonClass: 'spotathon_form'
        });

        $('#new_illustration').ajaxForm({
          dataType:  'script',
          beforeSubmit: function(){$.blockUI()},
          success: function(){$.unblockUI()},
          error: function (xhr,status,error) {delay()}
        });
        document.getElementById("uploadBtn1").onchange = function() {
            if (this.files[0].size/(1024*1024) > 5){
              document.getElementById("uploadFile1").value = '';
              alert("File size must be less than 5MB");
            }else{document.getElementById("uploadFile1").value = this.value;}
        };
        document.getElementById("uploadBtn2").onchange = function() {
            if (this.files[0].size/(1024*1024) > 5){
              document.getElementById("uploadFile2").value = '';
              alert("File size must be less than 5MB");
            }else{document.getElementById("uploadFile2").value = this.value;}
        };
      });
      function delay(){
        var t  = setTimeout(liftBlock, 10000);
        $('#myDiv').load(myUrl, function() {
          clearTimeout(t);
        });
      };
      function liftBlock() {
        $('.blockMsg').append('<button type="button" class="close mypopup-close upload-close" id="closeBlock" aria-label="Close"><span aria-hidden="true"><i class="fa fa-times"></i> Close</span></button>');
        $('#closeBlock').bind('click', $.unblockUI);
      };

      $("#illustration_tag_list").on('autocompleteresponse', function(event, ui) {
        var content;
        if (((content = ui.content) != null ? content[0].id.length : void 0) === 0) {
          $(this).autocomplete('close');
        }
      });

      function validateForm(){
        var main_image_name = $("#illustration_name").val().trim()
        var key_image_name = $("#answer_key").val().trim()
        if( main_image_name != '' && key_image_name != '') {
          if (main_image_name == key_image_name) {
            alert("'Main image' and 'Answer key' names should be different");
            return false;
          }
          if (main_image_name_exist && key_image_name_exist){
            alert("Main and Key illustration names are already taken. Please use an alternate names.")
            return false
          }else if (main_image_name_exist){
            alert("Main illustration name is already taken. Please use an alternate name.");
            return false
          }else if(key_image_name_exist){
            alert("Key illustration name is already taken. Please use an alternate name.");
            return false
          }
        }

        if($("#tnc_checkbox").prop("checked")){
          return true;
        }
        else
        {
          alert("Please accept Terms and Conditions");
          return false;
        }
      }

      $('#tnc_checkbox').click(function() {
        if (!$(this).is(':checked')) {
          $('#sub_illustration').addClass("disabled");
        }
        else{
          $('#sub_illustration').removeClass("disabled");
        }
      });

      $("#confirm").click(function(){
        $('#confirm_form').css("display", "none");
      });

      function check_image_name_exist(name, type){
        $.ajax({
          url: "/contests/validate_illustration_name",
          type: 'POST',
          data: {image_name:name},
          dataType : "json",
          success : function(data) {
            if (type == "main_image"){
              main_image_name_exist = data["status"];
            }else if (type == "key_image"){
              key_image_name_exist = data["status"];
            }
          }
        });
      }
    </script>
  </div>
</div>

app/views/contests/_new_contest_details.html.erb
<%= render :partial => "dashboard/errors" %>

<div class="row about-row noborder">
  <section id="search-details-temp" style="margin: 30px 45px;" >
    
    <div class="col-md-12 col-sm-12">
      <label>Who is Ameena?</label> 
    </div>
    
    <div class="col-md-12 col-sm-12">
      <label>Here’s your chance to illustrate a book for Pratham Books StoryWeaver and get paid for it! </label> 
    </div>
    
    <div class="col-md-12 col-sm-12">
      <p>Some of us look at the word “tree” and doodle this:</p>
    </div>
    
    <div class="col-md-12 col-sm-12">
      <%= link_to image_tag("Ameena_sample.jpg", :size => "150x200"), "#" %>
    </div>
 
    <div class="col-md-12 col-sm-12">  
      <p>And others conjure up something like this:</p>
      <span>
        <%= link_to "https://storyweaver.org.in/illustrations/2958", "https://storyweaver.org.in/illustrations/2958" %>
        <br> or this: <br>
        <%= link_to "https://storyweaver.org.in/illustrations/2762", "https://storyweaver.org.in/illustrations/2762" %>
        <br>If you belong to the second category, then this contest is right up your alley!
      </span>
      <br>
      <br>
      <label>Who is Ameena?</label>
      <br>
      <span>
        We have got a fabulous story coming up - <label>What is Ameena Up To?</label>, written by Roopa Banerjee. It is a charming story about a girl called Ameena and the antics she gets up to when her family isn't looking. We know Ameena is a mischievous little girl with a big imagination. 
      </span>
      <br> 
      <br> 
      <span>
        But what does she look like? What does her family and her home look like? <label>All of that is up to you!</label> This is your chance to illustrate a children’s book for Pratham Books StoryWeaver!
      </span> 
      <br>
      <br>
      <label>How to enter</label>
      <br>
      <span>Here is an extract from the story ‘What is Ameena Upto?’ <%= link_to "here", "https://storyweaver.org.in/search?utf8=%E2%9C%93&search%5Bquery%5D=What+is+Ameena+Upto%3F&button=" %></span>
    </div>   

    <div class="col-md-12 col-sm-12">  
      <p>We want you to draw Ameena. Upload your illustration on StoryWeaver and then send us a brief note to storyweaver@prathambook.org telling us your vision and how you would illustrate this story.</p><br>
      <p>The contest will be judged by award-winning illustrator, art director, writer, editor and overall publishing rockstar, inayakVarma. If we like your Ameena and vision the most, you will be chosen to sign a contract with us. You will get two months to illustrate the whole book, which will be published by Pratham Books on StoryWeaver. And yes, it’s a paid contract. </p>
    </div>
   
    <div class="col-md-12 col-sm-12">  
      <p>This is a Level 1 story, which is for children who are eager to begin reading. This is how pages of level 1 books look:</p>
      <label>include level 1 sample pages +++<label>
    </div>   

    <div class="col-md-12 col-sm-12">  
		  <label>Contest Guidelines</label>
				<p>1. The contest will run from August 7, 2017, to August 20, 2017</p>
				<p><label>2. Include size of file and specs +++</label></p>
				<p>3. Please send your illustration notes to storyweaver@prathambooks.org.</p>
				<p>4. Participants must be over the age of 17 to participate.</p>
				<p>5. By submitting your work to Retell, Remix and Rejoice 2017, you are agreeing to a CC-BY license being applied to it (This license lets others distribute, remix, tweak, and build upon your work, even commercially, as long as they credit you for the original creation). To know more about CC-BY, click <%= link_to "here", "https://creativecommons.org/licenses/by/4.0/" %>.</p>
    </div>

      <div class="row">
        <div class="col-lg-12">
          <%#= link_to "Enter contest now", new_story_path(contest_id: @contest.id) , remote: true, class: "btn btn-warning btn-lg hide-in-mob-create contest_story_create_button"%>
          <%= link_to "Enter Contest", illustrations_path(contest_id: @contest.id), class: "btn btn-warning btn-lg hide-in-mob-create contest_story_create_button" %>
          <div id="newStoryForm">
          </div>
        </div>
      </div>

      </section>

<%= render :partial => "stories/desktop_only_action_message" %>