config/routes.rb
Rails.application.routes.draw do
  root 'react#index'
  #Added v0 prefix to all rails routes
  #Rails routes blocking offline saving if no prefix
  scope :v0 do

    get "/blog" => "blog_posts#index", as: :v0_blog_posts
    post "/blog" => "blog_posts#create", as: :v0_create_blog_post
    get '/blog/search', to: 'blog_posts#search', as: :v0_blog_search
    get '/blog/dashboard', to: 'blog_posts#dashboard', as: :v0_blog_dashboard
    get '/blog/drafts', to: 'blog_posts#drafts', as: :v0_blog_drafts
    get '/blog/scheduled_posts', to: 'blog_posts#scheduled_posts', as: :v0_blog_scheduled_posts
    get '/blog/de_activated', to: 'blog_posts#de_activated', as: :v0_blog_de_activated
    get '/blog/new_comments', to: 'blog_posts#new_comments', as: :v0_new_comments
    resources :blog_posts,  except: [:create, :index] do
      get :autocomplete_tag_name, :on => :collection
      resources :comments, only: [:create, :destroy]
    end

    # devise_for :users
    #devise_for :users, :skip=>[:omniauth_callbacks, :sessions], :controllers => { :registrations => 'registrations'}
    get '/lists/:id/download', to: "api/v1/lists#download", as: :list_download

    resources 'illustrations' do
      get :autocomplete_user_email, :on => :collection
      get :autocomplete_tag_name, :on => :collection
    end

    #Organization_routes
    get '/organizations/organization_sign_up_model', to: 'organizations#organization_sign_up_model', as: :organization_sign_up_model
    post '/organizations/organization_sign_up', to: 'organizations#organization_sign_up', as: :organization_sign_up
    get '/organizations/new_users', to: 'organizations#new_users', as: :new_users
    get '/organizations/organizations_list', to: 'organizations#organizations_list', as: :organizations_list
    get 'organizations/assign_org_role', to: 'organizations#assign_org_role', as: :assign_org_role
    get '/organizations/check_org_publisher', to: 'organizations#check_org_publisher', as: :check_org_publisher
    post '/organizations/add_org_logo', to: 'organizations#add_org_logo', as: :add_org_logo
    #get '/organizations/remove_site_role', to: 'organizations#remove_site_role', as: :remove_site_role
    get '/organizations/validate_org_name_country', to: 'organizations#validate_org_name_country', as: :validate_org_name_country
    get '/organizations/autocomplete', to: 'organizations#autocomplete', as: :organizations_autocomplete
    get 'organizations/remove_org_role_dialog', to: 'organizations#remove_org_role_dialog', as: :remove_org_role_dialog
    get 'organizations/remove_org_role', to: 'organizations#remove_org_role', as: :remove_org_role

    get '/illustrations/:id/new_flag_illustration', to: 'illustrations#new_flag_illustration' , as: :new_flag_illustration
    post '/illustrations/flag_illustration/:id', to: 'illustrations#flag_illustration' , as: :flag_illustration

    get '/illustrations/download/:id', to: 'illustrations#download', as: :download_illustrations
    get '/illustration-view/:id', to: 'illustrations#illustration_view', as: :view_illustration
    post '/illustrations/update_favorites', to: 'illustrations#update_favorites', as: :update_favorites
    post '/illustrations/reset_illustration_download_count', to: 'illustrations#reset_illustration_download_count', as: :reset_illustration_download_count

    resources 'stories',  except: [:show, :index] do
      resources 'pages' do
        get 'epub'
      end
      resources 'translations'
      resources 'relevels'
      member do
        patch 'publish'
      end
      get :autocomplete_tag_name, :on => :collection
    end
    get 'profile/change_translator' => 'profile#change_translator', as: :profile_change_translator

    get "/stories/new_story_from_illustration/:id", to: "stories#new_story_from_illustration", as: :new_story_from_illustration
    get "/stories/create_story_from_illustration", to: "stories#create_story_from_illustration", as: :create_story_from_illustration
    get '/stories/:id/editable', to: 'stories#editable' , as: :story_editor_editable
    post '/stories/reviewer_rating_comment', to: 'stories#reviewer_rating_comment', as: :reviewer_rating_comment
    get '/stories/edit_story_editor/:id', to: 'stories#edit_story_editor', as: :edit_story_editor
    patch '/stories/:id/assign_change_editor', to: 'stories#assign_change_editor', as: :assign_change_editor
    get '/stories/close_assign_dailog/:id', to: 'stories#close_assign_dailog', as: :close_assign_dailog
    post "/stories/recommend_story_on_home", to: "stories#recommend_story_on_home", as: :recommend_story_on_home
    get '/stories/download-story/:id', to: 'stories#download_story', as: :download_story
    post '/stories/reset_story_download_count', to: 'stories#reset_story_download_count', as: :reset_story_download_count

    get 'stories/show-in-iframe/:id', to: 'stories#show_in_iframe', as: :v0_show_story_in_iframe
    get 'stories/:id/story-review', to: 'stories#story_review', as: :story_review
    post 'stories/:id/reviewer-comments', to: "stories#reviewer_comments", as: :reviewer_comments
    get 'stories/review_next_story/:id', to: "stories#review_next_story", as: :review_next_story
    resources 'illustration_crops'

    # editor routes
    patch '/editor/:id/update_dummy_draft', to: "story_editor#update_dummy_draft", as: :update_dummy_draft
    get '/editor/story/user_email', to: 'story_editor#get_email', as: :story_editor_get_email
    get '/editor/story/:id', to: 'story_editor#story' , as: :story_editor
    get '/editor/illustration/:id', to: 'story_editor#illustration_for_crop' , as: :illustration_for_crop, :defaults => { :format => :json }
    post '/editor/:page_id/crop/:id', to: 'story_editor#crop_illustration' , as: :crop_illustration
    get '/editor/page/:id', to: 'story_editor#page_edit' , as: :page_edit
    put '/editor/page/:page_id/change_template/:id', to: 'story_editor#change_page_template' , as: :change_template
    put '/editor/story/:story_id/insert/:id', to: 'story_editor#insert_page' , as: :insert_page
    put '/editor/story/:story_id/duplicate/:id', to: 'story_editor#duplicate_page' , as: :duplicate_page
    delete '/editor/story/:story_id/delete/:id', to: 'story_editor#delete_page' , as: :delete_page
    post '/editor/page/:id/illustration', to: 'story_editor#update_page_illustration', as: :update_page_illustration
    get '/editor/page/:id/illustration', to: 'story_editor#remove_page_illustration', as: :remove_page_illustration
    post '/editor/page/:id/content', to: 'story_editor#update_page_content', as: :update_page_content
    post '/editor/page/:id/auto_save_content', to: 'story_editor#auto_save_content', as: :auto_save_content
    post '/editor/page/:id/save_content_on_blur', to: 'story_editor#save_content_on_blur', as: :save_content_on_blur
    post '/editor/story/:id/rearrange', to: 'story_editor#rearrange_page', as: :rearrange_page
    get '/editor/search/illustration', to: 'story_editor#search_illustration', as: :search_illustration
    get '/editor/new_illustration', to: 'story_editor#new_illustration', as: :editor_new_illustration
    post '/editor/create_illustration', to: 'story_editor#create_illustration', as: :editor_create_illustration
    get '/editor/story/:id/validate_pages', to: 'story_editor#validate_story_pages', as: :editor_validate_story_pages
    get '/editor/story/:id/publish', to: 'story_editor#publish_form', as: :editor_publish_story_form
    get '/editor/story/:id/edit_book_info', to: 'story_editor#edit_book_info', as: :editor_edit_book_info
    patch '/editor/story/:id/publish', to: 'story_editor#publish', as: :editor_publish_story
    patch '/editor/story/:id/update', to: 'story_editor#update', as: :editor_update_story
    patch '/editor/story/:id/update_book_info', to: 'story_editor#update_book_info', as: :editor_update_book_info
    get '/editor/autocomplete_user_email', to: 'story_editor#autocomplete_user_email', as: :autocomplete_user_email_path
    get '/editor/save_to_draft', to: 'story_editor#save_to_draft', as: :save_to_draft
    get '/editor/get-all-illustrations', to: 'story_editor#get_all_illustrations', as: :get_all_illustrations
    get '/editor/get-favourite-illustrations', to: 'story_editor#get_favourite_illustrations', as: :get_favourite_illustrations
    get '/editor/upload-illustration', to: 'story_editor#upload_illustration', as: :upload_illustration
    get '/editor/language_script', to: "story_editor#language_script", as: :story_language_script
    get "/editor/create", to: "stories#create_story", as: :create_story
    get "/editor/:story_id/translate", to: "translations#translate_story", as: :translate_story
    get "/editor/:story_id/relevel", to: "relevels#relevel_story", as: :relevel_story

    # illustration tags
    get '/illustration/edit-tags/:id', to: 'illustrations#edit_tags', as: :edit_illustration_tags
    patch '/illustration/:id/update-tags', to: 'illustrations#update_tags', as: :update_illustration_tags
    get 'illustration/:id/used_stories', to: 'illustrations#illustration_used_in_stories', as: :illustration_used_in_stories
    #contest routes
    get 'contests/:id/contest_winners_details', to: 'contests#contest_winners_details', as: :contest_winners_details
    resources :contests
    get '/contests/:id/details', to: 'contests#contest_details', as: :contest_details
    #contest_illustrations
    post '/illustrations/contest_image', to: 'illustrations#contest_image', as: :contest_image
    get '/contests/:id/submitted_stories', to: 'contests#submitted_stories', as: :contest_submitted_stories
    post '/contests/story_rating_comments', to: 'contests#story_rating_comments', as: :story_rating_comments
    post '/contests/user_update_rating_comments', to: 'contests#user_update_rating_comments', as: :user_update_rating_comments
    post '/contests/user_update_rating_without_comments', to: 'contests#user_update_rating_without_comments', as: :user_update_rating_without_comments

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authorize_action, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]
  before_action :blog_list
  respond_to :html
  autocomplete :tag, :name, :class_name => 'ActsAsTaggableOn::Tag'

  EVERYTHING = "*"
  PER_PAGE = 3

  DEFAULT_CRITERIA = [
    { _score: {order: :desc} },
    { updated_at: {order: :desc} }
  ]


  def index
    results = process_search
    @blog_posts = results.execute
    respond_with(@blog_posts)
  end

  def show
    BlogPost.increment!(params[:id], :reads)
    respond_with(@blog_post)
  end

  def new
    @blog_post = BlogPost.new
    respond_with(@blog_post)
  end

  def edit
  end

  def create
    params[:blog_post][:published_at] = Time.now.strftime("%Y-%m-%d %H:%M:%S") if params[:blog_post][:status]=="published"
    @blog_post = BlogPost.new(blog_post_params)
    @blog_post.user = current_user
    flash[:notice] = "#{@blog_post.title} was successfully created." if @blog_post.save
    respond_with(@blog_post)
  end

  def update
    if params[:blog_post][:status]=="published"
      params[:blog_post][:published_at] = Time.now.strftime("%Y-%m-%d %H:%M:%S") unless @blog_post.status == "published"
    end
    params[:blog_post][:user_id] = current_user.id
    flash[:notice] = "#{@blog_post.title} was successfully Updated."  if @blog_post.update(blog_post_params)
    respond_with(@blog_post)
  end

  def destroy
    @blog_post.destroy
    respond_with(@blog_post)
  end

  def blog_list
    @blog_search = true
    conditions = {}
    conditions[:status] = Story.statuses[:published]
    blog_posts = BlogPost.where(conditions)
    @blog_posts_by_tags = {}
    blog_posts_by_tags = blog_posts.map {|b| b.tag_list.map{|t|  @blog_posts_by_tags[t] ||= 0; @blog_posts_by_tags[t] += 1}}
    @blog_posts_by_month = blog_posts.group_by { |t| t.created_at.beginning_of_month }
    @blog_actions_authorization = true if current_user && (current_user.content_manager? || current_user.promotion_manager?)
  end

  def search
    @search_query = search_params[:query]
    results = process_search
    @blog_posts = results.execute
    render :file => 'blog_posts/index'
  end

  def dashboard
    @current_tab = 'published'
    @blog_posts = BlogPost.where(:status => BlogPost.statuses[:published]).order(published_at: :desc)
  end

  def drafts
    @current_tab = 'drafts'
    @blog_drafts = BlogPost.where(:status => BlogPost.statuses[:draft]) 
  end

  def de_activated
    @current_tab = 'de_activated'
    @blog_de_activated = BlogPost.where(:status => BlogPost.statuses[:de_activated]).page(params[:page]).per(10)
  end

  def new_comments
    @current_tab = 'new_comments'
    @comments = Comment.all.order(created_at: :desc) 
  end

  def scheduled_posts
    @current_tab = 'scheduled'
    @blog_scheduled_posts = BlogPost.where(:status => BlogPost.statuses[:scheduled]).page(params[:page]).per(10)
  end

  def process_search
    filters = filters()
    order_criteria = BlogPost.count > 0 ? sort_params || DEFAULT_CRITERIA : []
    query = BlogPost.search(
      search_params[:query].blank? ? EVERYTHING : search_params[:query],
      page: params[:page],
      per_page: params[:per_page] || PER_PAGE,
      operator: "or",
      fields:['title^20', 'tags_name^10'],
      where: filters,
      order: order_criteria,
      load: false,
      execute: false)
    return query
  end

  def search_params
    if params[:search].blank?
      {query: nil, tags_name: nil, archive: nil}
    else
      search_params = params.require(:search).permit(
        :query,
        :tag_name,
        :archive,
        sort:[

          {
            updated_at: :order
          }
        ]
      )
      search_params
    end
  end

  def filters
    filters = {}
    filters[:tags_name] = search_params[:tag_name] unless search_params[:tag_name].nil? || search_params[:tag_name].empty?
    filters[:archive] = search_params[:archive] unless search_params[:archive].nil? || search_params[:archive].empty?
    filters[:status] = [:published]
    return filters
  end

  def sort_params
    sort = nil
    if params[:sort]
      sort = [
        {
          language: {order: params[:direction]=='asc' ? :asc : :desc}
        }
      ]
    end
    sort
  end

  private
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    def authorize_action
      authorize self, :default
    end

    def blog_post_params
      params.require(:blog_post).permit(:title, :body, :status, :scheduled, :published_at, :comments_count, :user_id, :tag_list, :blog_post_image)
    end
end

app/views/blog_posts/_form.html.erb
<%= simple_form_for @blog_post , url: (@blog_post.new_record? ? create_blog_post_path(@blog_post) : @blog_post), method: (@blog_post.new_record? ? :post : :put) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs blog_post_image">
    <%= f.input :title %>
    <%= f.cktext_area :body %>
    <%= f.input :status, collection: BlogPost.statuses.keys, selected: BlogPost.statuses.keys.first, input_html: {:style =>"width: 185px;" } %>
    <%= f.input :scheduled, as: :string, input_html:  { :class => "form-control" }, input_html: {:style =>"width: 185px;" } %>
    <%= f.input :tag_list,  label: "Tags", url: autocomplete_tag_name_blog_posts_path,as: :autocomplete,input_html: {'data-delimiter' => ','}   %>
    <%#= f.file_field :blog_post_image, :id=> "logo", as: :file , :class => "user_logo blog_post_img" %>
  </div>

  <div class="form-actions create_blog_post">
    <%= f.button :submit %>
  </div>
<% end %>

<script>
  if ($('#blog_post_status').val() == "scheduled"){
    $(".blog_post_scheduled").show();
  }else $(".blog_post_scheduled").hide();
  $('#blog_post_scheduled').datetimepicker({format:'Y-m-d H:i:s'});
  $("#blog_post_status").on('change', function(){
    if ($(this).val() == "scheduled"){
      $(".blog_post_scheduled").show();
    }else $(".blog_post_scheduled").hide();
  });

</script>

app/views/blog_posts/_tabs.html.erb
<div class="row full-content-dash">
  <div class="col-md-12">
    <ul class="nav nav-tabs content-manager" role="tablist" id="myTab">
      <li role="presentation" class="<%= @current_tab == 'published' ? 'active' : '' %>">
        <%= link_to "<span>Published Posts</span>".html_safe , blog_dashboard_path %>
      </li>
      <li role="presentation" class="<%= @current_tab == 'drafts' ? 'active' : '' %>">
        <%= link_to "<span>Drafts</span>".html_safe , blog_drafts_path %>
      </li>
      <li role="presentation" class="<%= @current_tab == 'scheduled' ? 'active' : '' %>">
        <%= link_to "<span>Scheduled Posts</span>".html_safe, blog_scheduled_posts_path  %>
      </li>
      <li role="presentation" class="<%= @current_tab == 'de_activated' ? 'active' : '' %>">
        <%= link_to "<span>Deactivated Posts</span>".html_safe, blog_de_activated_path   %>
      </li>
      <li role="presentation" class="<%= @current_tab == 'new_comments' ? 'active' : '' %>">
        <%= link_to "<span>New comments</span>".html_safe, new_comments_path   %>
      </li>
    </ul>
  </div>
  <hr />
</div>

app/views/blog_posts/dashboard.html.erb
<%= render :partial => "dashboard/dashboard_datatables" %>

<%= render :partial => "tabs" %>

<div class="row">
  <div class="col-md-12 col-sm-12">
  	<label class="allusers">
      <span>Number of Blogs selected :</span>
      <span class="badge" id="blogs_count"><%= @blog_posts.count %></span>
    </label>
  </div>
</div>


<div role="tabpanel" class="tab-pane" id="profile-drafts">
  <div class="col-md-12">
    <table class="table table-striped" id="blogs">
      <tfoot style="display: table-header-group;">
        <tr>
          <th>Title</th>
          <th>Created at</th>
          <th>Comments</th>
          <th>Reads</th>
          <th></th>
          <th></th>
        </tr>
      </tfoot>
      <thead>
        <tr class="table-heading-row">
          <th>Title</th>
          <th>Created at</th>
          <th>Comments</th>
          <th>Reads</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody class="table-row-details">
        <% @blog_posts.each do |blog_post| %>
          <tr class="selected_blogs">
            <td><%= link_to blog_post.title, blog_post_path(blog_post.id) %></td>
            <td><%= blog_post.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
            <td><%= blog_post.comments_count %></td>
            <td><%= blog_post.reads %></td>
            <td><%= link_to 'Edit', edit_blog_post_path(blog_post.id), class:"btn btn-info edit-btn" %></td>
            <td><%= link_to 'Destroy', blog_post_path(blog_post.id), class:"btn btn-info edit-btn", method: :delete, data: { confirm: 'Are you sure?' }, "data-confirm-title" => "StoryWeaver", "data-confirm-cancel" => "Cancel", "data-confirm-cancel-class" => "btn btn-info btn-grey", "data-confirm-proceed" => "Ok", "data-confirm-proceed-class" => "btn-info edit-btn" %></td>

          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= link_to 'Write new post', new_blog_post_path, :class => "btn btn-info edit-btn submit-comment", :role => "button" if @blog_actions_authorization%>
</div>

<script>
$(document).ready(function() {
  var table = $('#blogs').DataTable( {
    searching: true,
    lengthChange: false,
    showNEntries: false,
    pageLength: 20,
    order: [],
    responsive: {
        details: false
    },
    dom: '<"col-md-6 col-sm-6"B><"col-md-6 col-sm-6"f><"col-md-12 col-sm-12"p>rti',
    buttons: [
              {
                  extend: 'copyHtml5',
                  title: formatDatatableTitle('posts'),
                  exportOptions: {
                      columns: [ 0, 1, 2, 3, 4 ]
                  }
              },
              {
                  extend: 'csvHtml5',
                  title: formatDatatableTitle('posts'),
                  exportOptions: {
                      columns: [ 0, 1, 2, 3, 4 ]
                  }
              },
              {
                  extend: 'excelHtml5',
                  title: formatDatatableTitle('posts'),
                  exportOptions: {
                      columns: [ 0, 1, 2, 3, 4 ]
                  }
              },
              {
                  extend: 'pdfHtml5',
                  title: formatDatatableTitle('posts'),
                  exportOptions: {
                      columns: [ 0, 1, 2, 3, 4 ]
                  }
              }
          ]
      
  });
  $('#blogs tfoot th').each( function () {
      var title = $(this).text();
      $(this).html( '<input type="text" placeholder="Search '+title+'" />' );
  });

  var new_table = $('#blogs').dataTable();
  table.columns().every( function () {
    var that = this;

    $( 'input', this.footer() ).on( 'keyup change', function () {
      if ( that.search() !== this.value ) {
          that
              .search( this.value )
              .draw();
        document.getElementById("blogs_count").innerHTML = document.getElementById('blogs').children[1].childElementCount;
      }else{
        document.getElementById("blogs_count").innerHTML = table.rows( '.selected_blogs' ).count(); 
      }
    });
  });
  $( 'input').on( 'keyup change', function () {
    document.getElementById("blogs_count").innerHTML = new_table.fnSettings().fnRecordsDisplay();
  });

  });

</script>

app/views/blog_posts/edit.html.erb
<h1>Editing blog_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/index.html.erb
<div class="home-full-border">
  <div class="blog-page-cont">
    <div class="container">
      <div class="row row-offcanvas row-offcanvas-left">

        <%= render :partial => "blog_nav" %>

        <div class="col-xs-12 col-sm-9 blog_posts">
          <div class="blog_mob_search">
            <form class="navbar-form" role="search">
              <div class="input-group add-on">
                <input class="form-control" placeholder="Search" name="srch-term" id="srch-term" type="text">
                <div class="input-group-btn">
                  <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                </div>
              </div>
            </form>
          </div>
          <%= link_to 'New Blog post', new_blog_post_path, :class => "btn btn-info edit-btn submit-comment", :role => "button" if @blog_actions_authorization%>
          <% @blog_posts.each do |blog_post| %>
            <div class="blog-header">
              <h1><%=link_to blog_post.title, blog_post_path(blog_post.url_slug), :style => "line-height: 45px !important;" %></h1>
              <% if blog_post.published_at.present? %><span class="posted_at">Posted by <i><%= blog_post.blogger %></i> on <%= blog_post.published_at.to_date.strftime("%B %d, %Y") %></span><% end %>
            </div>
            <%= raw blog_post.body %>
            <%= social_share_button_tag(blog_post.title, :url => "#{request.base_url}#{blog_post_path(blog_post.url_slug)}" ,:popup => "true") %>
            <% if @blog_actions_authorization %>
              <%= link_to 'Edit', edit_blog_post_path(blog_post.url_slug), :class => "btn btn-info edit-btn", :role => "button", :style => "float:left;"%>
              <%= link_to 'Destroy', blog_post_path(blog_post.id), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-info edit-btn", :role => "button", :style => "float:left;" %>
            <% end %>
            <% comments = blog_post.comments_count > 0 ? "comment#{blog_post.comments_count > 1? 's' : ''} (#{blog_post.comments_count}) " : "Be the first to comment."%>
            <% unless @blog_actions_authorization %>
              <i class="fa fa-comments fa-lg"></i>
              <%= link_to comments, blog_post_path(blog_post.url_slug, :anchor => "comments") %>
            <% end %>
            </br/>
            <hr/>
          <% end %>
          <div class="blog-pagination">
            <% unless @blog_posts.first_page? %><%= link_to_previous_page @blog_posts, "<span class='glyphicon glyphicon-circle-arrow-left'></span> Previous".html_safe, :params => params %><% end %>
            <%= link_to(blog_posts_path) do %>
              <span class="glyphicon glyphicon-home" style="left:41%"></span>
            <%end%>
            <%unless @blog_posts.last_page? %><%= link_to_next_page @blog_posts, "Next <span class='glyphicon glyphicon-circle-arrow-right' style='float:right;margin-left: 3px; margin-top: 3px;'></span>".html_safe, :style => "float:right;", :params => params %><% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/blog_posts/new.html.erb
<h1>New blog_post</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<div class="home-full-border">
  <div class="blog-page-cont">
    <div class="container">
      <div class="row row-offcanvas row-offcanvas-left">

        <%= render :partial => "blog_nav" %>

        <div class="col-xs-12 col-sm-9  blog_posts">
          <div class="blog_mob_search">
            <form class="navbar-form" role="search">
              <div class="input-group add-on">
                <input class="form-control" placeholder="Search" name="srch-term" id="srch-term" type="text">
                <div class="input-group-btn">
                  <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                </div>
              </div>
            </form>
          </div>
          <div class="blog-header">
            <h1><%= @blog_post.title %></h1>
            <% if @blog_post.published_at.present? %><span class="posted_at">Posted by <i><%= @blog_post.user.name %></i> on <%= @blog_post.published_at.to_date.strftime("%B %d, %Y") %></span><% end %>
          </div>
          <%= raw @blog_post.body.html_safe %>
          <%= social_share_button_tag(@blog_post.title, :url => "#{request.base_url}#{blog_post_path(@blog_post.id)}" ,:popup => "true") %>
          <% if @blog_actions_authorization %>
            <%= link_to 'Edit', edit_blog_post_path(@blog_post), :class => "btn btn-info edit-btn", :role => "button", :style => "float:left;"%>
            <%= link_to 'Back', blog_posts_path, :class => "btn btn-info edit-btn", :role => "button", :style => "float:left;"%>
          <% end %>
          <br/>
          <hr/>
          <h2><i class="fa fa-comments"></i><%= @blog_post.comments_count %><%= @blog_post.comments_count == 1 ? ' Comment' : ' Comments'%> </h2>
          <div id="comments">
            <%= render :partial => @blog_post.comments %>
          </div>
          <%= simple_form_for(([@blog_post, @blog_post.comments.build]), :remote=> true) do |f| %>
            <%= f.input :body, label: false %>
            <% if current_user %>
              <%= f.button :submit, "Post comment", :class => "btn btn-info edit-btn submit-comment"%>
            <% else %>
              <a class = "btn btn-info edit-btn submit-comment" href="/users/sign_in">Post comment</a>
            <% end %>
          <% end %>
          <div class="blog-pagination">
            <% unless @blog_post.previous.nil? %><%= link_to @blog_post.previous do %><span class="glyphicon glyphicon-circle-arrow-left"></span> Previous<%end %><%end %>
            <%= link_to(blog_posts_path) do %>
              <span class="glyphicon glyphicon-home" style="left:41%"></span>
            <%end%>
            <% unless @blog_post.next.nil? %><%= link_to @blog_post.next , :style=>"float:right;" do %>Next <span class="glyphicon glyphicon-circle-arrow-right"></span><%end %><% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>