config/routes.rb
    get '/blog/dashboard', to: 'blog_posts#dashboard', as: :v0_blog_dashboard
    get '/blog/drafts', to: 'blog_posts#drafts', as: :v0_blog_drafts
    get '/blog/scheduled_posts', to: 'blog_posts#scheduled_posts', as: :v0_blog_scheduled_posts
    get '/blog/de_activated', to: 'blog_posts#de_activated', as: :v0_blog_de_activated
    get '/blog/new_comments', to: 'blog_posts#new_comments', as: :v0_new_comments
    resources :blog_posts,  except: [:create, :index] do
      get :autocomplete_tag_name, :on => :collection
      resources :comments, only: [:create, :destroy]
    end

    # devise_for :users
    #devise_for :users, :skip=>[:omniauth_callbacks, :sessions], :controllers => { :registrations => 'registrations'}
    get '/lists/:id/download', to: "api/v1/lists#download", as: :list_download

    resources 'illustrations' do
      get :autocomplete_user_email, :on => :collection
      get :autocomplete_tag_name, :on => :collection
    end

    #Organization_routes
    get '/organizations/organization_sign_up_model', to: 'organizations#organization_sign_up_model', as: :organization_sign_up_model
    post '/organizations/organization_sign_up', to: 'organizations#organization_sign_up', as: :organization_sign_up
    get '/organizations/new_users', to: 'organizations#new_users', as: :new_users
    get '/organizations/organizations_list', to: 'organizations#organizations_list', as: :organizations_list
    get 'organizations/assign_org_role', to: 'organizations#assign_org_role', as: :assign_org_role
    get '/organizations/check_org_publisher', to: 'organizations#check_org_publisher', as: :check_org_publisher
    post '/organizations/add_org_logo', to: 'organizations#add_org_logo', as: :add_org_logo
    #get '/organizations/remove_site_role', to: 'organizations#remove_site_role', as: :remove_site_role
    get '/organizations/validate_org_name_country', to: 'organizations#validate_org_name_country', as: :validate_org_name_country
    get '/organizations/autocomplete', to: 'organizations#autocomplete', as: :organizations_autocomplete
    get 'organizations/remove_org_role_dialog', to: 'organizations#remove_org_role_dialog', as: :remove_org_role_dialog
    get 'organizations/remove_org_role', to: 'organizations#remove_org_role', as: :remove_org_role

    get '/illustrations/:id/new_flag_illustration', to: 'illustrations#new_flag_illustration' , as: :new_flag_illustration
    post '/illustrations/flag_illustration/:id', to: 'illustrations#flag_illustration' , as: :flag_illustration

    get '/illustrations/download/:id', to: 'illustrations#download', as: :download_illustrations
    get '/illustration-view/:id', to: 'illustrations#illustration_view', as: :view_illustration
    post '/illustrations/update_favorites', to: 'illustrations#update_favorites', as: :update_favorites
    post '/illustrations/reset_illustration_download_count', to: 'illustrations#reset_illustration_download_count', as: :reset_illustration_download_count

    resources 'stories',  except: [:show, :index] do
      resources 'pages' do
        get 'epub'
      end
      resources 'translations'
      resources 'relevels'
      member do
        patch 'publish'
      end
      get :autocomplete_tag_name, :on => :collection
    end
    get 'profile/change_translator' => 'profile#change_translator', as: :profile_change_translator

    get "/stories/new_story_from_illustration/:id", to: "stories#new_story_from_illustration", as: :new_story_from_illustration
    get "/stories/create_story_from_illustration", to: "stories#create_story_from_illustration", as: :create_story_from_illustration
    get '/stories/:id/editable', to: 'stories#editable' , as: :story_editor_editable
    post '/stories/reviewer_rating_comment', to: 'stories#reviewer_rating_comment', as: :reviewer_rating_comment
    get '/stories/edit_story_editor/:id', to: 'stories#edit_story_editor', as: :edit_story_editor
    patch '/stories/:id/assign_change_editor', to: 'stories#assign_change_editor', as: :assign_change_editor
    get '/stories/close_assign_dailog/:id', to: 'stories#close_assign_dailog', as: :close_assign_dailog
    post "/stories/recommend_story_on_home", to: "stories#recommend_story_on_home", as: :recommend_story_on_home
    get '/stories/download-story/:id', to: 'stories#download_story', as: :download_story
    post '/stories/reset_story_download_count', to: 'stories#reset_story_download_count', as: :reset_story_download_count

    get 'stories/show-in-iframe/:id', to: 'stories#show_in_iframe', as: :v0_show_story_in_iframe
    get 'stories/:id/story-review', to: 'stories#story_review', as: :story_review
    post 'stories/:id/reviewer-comments', to: "stories#reviewer_comments", as: :reviewer_comments
    get 'stories/review_next_story/:id', to: "stories#review_next_story", as: :review_next_story
    resources 'illustration_crops'

    # editor routes
    patch '/editor/:id/update_dummy_draft', to: "story_editor#update_dummy_draft", as: :update_dummy_draft
    get '/editor/story/user_email', to: 'story_editor#get_email', as: :story_editor_get_email
    get '/editor/story/:id', to: 'story_editor#story' , as: :story_editor
    get '/editor/illustration/:id', to: 'story_editor#illustration_for_crop' , as: :illustration_for_crop, :defaults => { :format => :json }
    post '/editor/:page_id/crop/:id', to: 'story_editor#crop_illustration' , as: :crop_illustration
    get '/editor/page/:id', to: 'story_editor#page_edit' , as: :page_edit
    put '/editor/page/:page_id/change_template/:id', to: 'story_editor#change_page_template' , as: :change_template
    put '/editor/story/:story_id/insert/:id', to: 'story_editor#insert_page' , as: :insert_page
    put '/editor/story/:story_id/duplicate/:id', to: 'story_editor#duplicate_page' , as: :duplicate_page
    delete '/editor/story/:story_id/delete/:id', to: 'story_editor#delete_page' , as: :delete_page
    post '/editor/page/:id/illustration', to: 'story_editor#update_page_illustration', as: :update_page_illustration
    get '/editor/page/:id/illustration', to: 'story_editor#remove_page_illustration', as: :remove_page_illustration
    post '/editor/page/:id/content', to: 'story_editor#update_page_content', as: :update_page_content
    post '/editor/page/:id/auto_save_content', to: 'story_editor#auto_save_content', as: :auto_save_content
    post '/editor/page/:id/save_content_on_blur', to: 'story_editor#save_content_on_blur', as: :save_content_on_blur
    post '/editor/story/:id/rearrange', to: 'story_editor#rearrange_page', as: :rearrange_page
    get '/editor/search/illustration', to: 'story_editor#search_illustration', as: :search_illustration
    get '/editor/new_illustration', to: 'story_editor#new_illustration', as: :editor_new_illustration
    post '/editor/create_illustration', to: 'story_editor#create_illustration', as: :editor_create_illustration
    get '/editor/story/:id/validate_pages', to: 'story_editor#validate_story_pages', as: :editor_validate_story_pages
    get '/editor/story/:id/publish', to: 'story_editor#publish_form', as: :editor_publish_story_form
    get '/editor/story/:id/edit_book_info', to: 'story_editor#edit_book_info', as: :editor_edit_book_info
    patch '/editor/story/:id/publish', to: 'story_editor#publish', as: :editor_publish_story
    patch '/editor/story/:id/update', to: 'story_editor#update', as: :editor_update_story
    patch '/editor/story/:id/update_book_info', to: 'story_editor#update_book_info', as: :editor_update_book_info
    get '/editor/autocomplete_user_email', to: 'story_editor#autocomplete_user_email', as: :autocomplete_user_email_path
    get '/editor/save_to_draft', to: 'story_editor#save_to_draft', as: :save_to_draft
    get '/editor/get-all-illustrations', to: 'story_editor#get_all_illustrations', as: :get_all_illustrations
    get '/editor/get-favourite-illustrations', to: 'story_editor#get_favourite_illustrations', as: :get_favourite_illustrations
    get '/editor/upload-illustration', to: 'story_editor#upload_illustration', as: :upload_illustration
    get '/editor/language_script', to: "story_editor#language_script", as: :story_language_script
    get "/editor/create", to: "stories#create_story", as: :create_story
    get "/editor/:story_id/translate", to: "translations#translate_story", as: :translate_story
    get "/editor/:story_id/relevel", to: "relevels#relevel_story", as: :relevel_story

    # illustration tags
    get '/illustration/edit-tags/:id', to: 'illustrations#edit_tags', as: :edit_illustration_tags
    patch '/illustration/:id/update-tags', to: 'illustrations#update_tags', as: :update_illustration_tags
    get 'illustration/:id/used_stories', to: 'illustrations#illustration_used_in_stories', as: :illustration_used_in_stories
    #contest routes
    get 'contests/:id/contest_winners_details', to: 'contests#contest_winners_details', as: :contest_winners_details
    resources :contests
    get '/contests/:id/details', to: 'contests#contest_details', as: :contest_details
    #contest_illustrations
    post '/illustrations/contest_image', to: 'illustrations#contest_image', as: :contest_image
    get '/contests/:id/submitted_stories', to: 'contests#submitted_stories', as: :contest_submitted_stories
    post '/contests/story_rating_comments', to: 'contests#story_rating_comments', as: :story_rating_comments
    post '/contests/user_update_rating_comments', to: 'contests#user_update_rating_comments', as: :user_update_rating_comments
    post '/contests/user_update_rating_without_comments', to: 'contests#user_update_rating_without_comments', as: :user_update_rating_without_comments
    get 'contests/:id/contest_draft_stories', to: 'contests#contest_draft_stories', as: :contest_draft_stories
    get 'contests/:id/illustration_contest_form', to: 'contests#illustration_form', as: :illustration_contest_form
    post 'contests/:id/create_illustration', to: 'contests#create_illustration', as: :create_illustration

app/views/stories/_assign_change_editor.html.erb
<label>Editor:</label>
<% if @story.editor_id != nil %>
     <%= @story.editor.name %>
    <span><%= link_to "Change", edit_story_editor_path, :remote => true  if current_user && current_user.content_manager?%></span>
    <span><%= link_to "Remove", delete_editor_modal_path(:story_id => @story.id, :path => "story_details"), :remote => true  if current_user && current_user.content_manager?%></span>
<% else %>
<span><%= link_to "Assign", edit_story_editor_path, :remote => true  if current_user && current_user.content_manager?%></span>
<% end %>

app/views/stories/_bulk_download_stories_list.html.erb
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h2 class="modal-title text-left">Stories selected for bulk download</h2>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    </div>
    <div class="modal-body modal-body-app">
      <div class="row">
        <table class="table table-striped">
          <thead>
            <tr class="table-heading-row">
              <th></th>
              <th>Story title</th>
              <th>Language</th>
              <th>Level</th>
            </tr>
          </thead>
          <tbody class="table-row-details">
            <% stories.each do|story| %>
              <tr>
                <td><input  class="final_selected_stories" data-story-id="<%=story.id%>" type="checkbox" name="selected_for_bulk" checked="checked"></td>
               <td><%= story.title %></td>
               <td><%= story.language.name %></td>
               <td><%= story.reading_level %></td>
              </tr> 
            <% end %>  
         </tbody>
        </table>
      </div> <!-- /row -->        
    </div> <!-- /modal-body -->
    <div class="modal-footer">
        <p id="validated_selected"> Please select atleast one story for download.</p>
      <div class="row row-gutter">
        <div class="text-right footer-container">
          <span class="gutter-sm-x vertical-i-top spacing-half-v">
            <span class="btn btn-app btn-brand-1" id="download_ok">Ok</span>
          </span>
          <span class="gutter-sm-x vertical-i-top spacing-half-v">
            <span class="btn btn-app btn-brand-1" id="cancel">Cancel</span>
          </span>
        </div>
      </div>
    </div> <!-- /modal-footer -->
  </div> <!-- /modal-content -->
</div> <!-- /modal-dialog -->

app/views/stories/_desktop_only_action_message.html.erb
<div id="hide_mobile_translate" class="hide_mobile_dialog" title="Message">
    Looks like you want to do more on StoryWeaver! To translate a story please log-in using a desktop/laptop.
</div>
<div id="hide_mobile_relevel" class="hide_mobile_dialog" title="Message">
    Looks like you want to do more on StoryWeaver! To re-level a story please log-in using a desktop/laptop.
</div>
<div id="hide_mobile_edit" class="hide_mobile_dialog" title="Message">
    Looks like you want to do more on StoryWeaver! To edit a story please log-in using a desktop/laptop.
</div>
<div id="hide_mobile_upload" class="hide_mobile_dialog" title="Message">
    Looks like you want to do more on StoryWeaver! To upload an image please log-in using a desktop/laptop.
</div>
<div id="hide_mobile_create" class="hide_mobile_dialog" title="Message">
    Looks like you want to do more on StoryWeaver! To create a story you need to log-in using a desktop/laptop.
</div>
<div id="hide_mobile_contest_story" class="hide_mobile_dialog" title="Message">
    Looks like you want to do more on StoryWeaver! To create a story for "RetellRemixRejoice2016 Contest" you need to log-in using a desktop/laptop.
</div>
<script>
$(".hide_mobile_dialog").dialog({
      autoOpen: false,
      width: 300,
      modal: true,
      buttons : {
      	"Ok" : function() {
        $(this).dialog("close");
      	}
      },
      dialogClass: 'change_orientation_dialog'
    });
if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
 jQuery(document).ready(function ($) {
   $(".hide-in-mob, .hide-in-translate a").click(function (evt) {
   	evt.preventDefault();
   	var dialogElement = $("#hide_mobile_translate.hide_mobile_dialog");
        dialogElement.dialog("open");
      return false;
   });
   $(".hide-in-relevel a").click(function (evt) {
    evt.preventDefault();
    var dialogElement = $("#hide_mobile_relevel.hide_mobile_dialog");
        dialogElement.dialog("open");
      return false;
   });
   $(".hide-in-edit a").click(function (evt) {
    evt.preventDefault();
    $("#edit_published_story_dialog").dialog("close")
    var dialogElement = $("#hide_mobile_edit.hide_mobile_dialog");
        dialogElement.dialog("open");
      return false;
   });
   $(".hide-in-mob-upload").click(function (evt) {
    evt.preventDefault();
    var dialogElement = $("#hide_mobile_upload.hide_mobile_dialog");
        dialogElement.dialog("open");
      return false;
   });
   $(".hide-in-mob-create").click(function (evt) {
    evt.preventDefault();
    var dialogElement = $("#hide_mobile_create.hide_mobile_dialog");
        dialogElement.dialog("open");
      return false;
   });
   $("#spotathon_contest").click(function (evt) {
      evt.preventDefault();
      var dialogElement = $("#hide_mobile_contest_story.hide_mobile_dialog");
          dialogElement.dialog("open");
        return false;
     });
});
}
</script>

app/views/stories/_iframe_for_review_form.html.erb
<% if @story.derivation_type != nil%>
  <% if @story.root.language.name != "English" && (@flag ? @story.get_english_version(@current_user) != nil : nil) %>
     <div class="row">
       <%= link_to "Click here for english version", story_review_path(:flag => false), class: "btn btn-normal btn-warning" %>
     </div>
  <% end %>
		<div class="row">
			 <div class="col-md-6">
				 <h3 style="margin-left:3%">Click on the image to read '<span class="<%= @story.language.script %>"><%= @flag ? @story.root.title.strip : @english_story.title.strip  %></span>' (Original)</h3>
				 <% iframe_style = (@flag ?  @story.root.orientation : @english_story.orientation ) == "landscape" ? 'height:380px;width:512px;margin-left:3%;' : 'height:439px;width:322px;margin-left:5%;' %>
				 <iframe src="<%=host_url%><%= show_story_in_iframe_path(@flag ? @story.root : @english_story, :iframe=>true, :disable_review_link => "disable_review_link")%>"
			 	   style="<%=iframe_style%>" allowfullscreen webkitallowfullscreen mozallowfullscreen></iframe>
		    </div>

		  <div class="col-md-6">
			 	<h3  style="margin-left:3%">
           Click on the image to read
           <% if @story.derivation_type == "translated" %>
              '<span class="<%= @story.language.script %>"><%= @story.title.strip %></span>'
                &nbsp;(Translation)
           <% else %>
              '<span class="<%= @story.language.script %>"><%= @story.title.strip %></span>'
               &nbsp;(Re-levelled)
           <% end %>
         </h3>
				<% iframe_style= @story.orientation=="landscape" ? 'height:380px;width:512px;margin-left:3%;' : 'height:439px;width:322px;margin-left:5%;' %>
				<iframe src="<%=host_url%><%= show_story_in_iframe_path(@story, :iframe=>true, :disable_review_link => "disable_review_link")%>"
			 	style="<%=iframe_style%>" allowfullscreen webkitallowfullscreen mozallowfullscreen></iframe>
		 	</div>
		 </div>
<% else %>
		<div class="story_iframe">
			<h3 style="margin-left:3%">Click on the image to read '<span class="<%= @story.language.script %>"><%= @story.title.strip %></span>'</h3>
			<% iframe_style= @story.orientation=="landscape" ? 'height:380px;width:512px' : 'height:439px;width:322px;margin-left:5%;' %>
			<iframe src="<%=host_url%><%= show_story_in_iframe_path(@story, :iframe=>true, :disable_review_link => "disable_review_link")%>"
			 style="<%=iframe_style%>" allowfullscreen webkitallowfullscreen mozallowfullscreen></iframe> 
		</div>
<% end%>
	<h2>Start Rating '<span class="<%= @story.language.script %>"><%= @story.title.strip %></span>'</h2>

app/views/stories/_new.html.erb
<div class="modal modal-image-drawer fade modal--story-creator" id="storyModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <%= simple_form_for @story, url: update_dummy_draft_path(:id=>@story), remote: true, html: { class: 'newStory',  multipart: true } do |f| %>
      <div class="modal-content">
        <div class="modal-body modal-body-app">
          <div class="form-group">
            <div class="spacing-half-v"></div>
            <div class="heading-title"><%= t 'editor.create_new_story_form.header'%></div>
            <div class="spacing-half-v"></div>
          </div>
          <div class="form-group form-group-lg-pad">
            <label class="heading-section label-required"><%= t 'dashboard.language'%></label>
            <% if @contest.present? %>
              <%= f.input :contest_id,  as: :hidden , :input_html => { :value => @contest.id } %>
                <%= f.association :language, collection: @contest.languages, label: false, prompt: "Choose Language", :input_html => {:class => "select-sm text-bold", :onChange=>"select_language();"} %>
            <% else %>
              <%= f.association :language, label: false, prompt: "Choose Language", :input_html => {:class => "select-sm text-bold", :onChange=>"select_language();"} %>
            <% end %>
          </div>
          <div class="form-disabled">
            <div class="form-group form-group-lg-pad">
              <label class="heading-section"><%= t 'editor.create_new_story_form.book_title'%></label>
              <div class="help-block help-block-brand">(<%= t 'editor.create_new_story_form.book_title_notification'%>)</div>
              <%= f.input :title ,label: false, required: true, input_html: { autocomplete: 'off', value: @story.user_title? ? @story.title.strip : '',  placeholder: "#{t 'editor.create_new_story_form.story_title_placeholder'}", class: "input-brand input-brand--lg english"} %>
            </div>

            <div class="form-group">
              <label class="heading-section label-required"><%= t 'dashboard.reading_level'%></label>
              <div class="radio radio-no-margin">
                <% if @contest.present? && @contest.name == "RetellRemixRejoice2018" %>
                  <%= f.input :reading_level, label: false, as: :radio_buttons, collection: Story::CONTEST_READING_LEVELS.collect {|key,value| ["<strong>Level #{key}:</strong> #{Story::READING_LEVEL_INFO[key]}".html_safe,key] }.compact%>
                <% else %>
                  <%= f.input :reading_level, label: false, as: :radio_buttons, collection: Story::READING_LEVELS.collect {|key,value| ["<strong>Level #{key}:</strong> #{Story::READING_LEVEL_INFO[key]}".html_safe,key] }.compact%>
                <% end %>
              </div> <!-- /radio -->
            </div>
            <div class="form-group">
              <label class="heading-section label-required"><%= t 'editor.create_new_story_form.book_orientation'%></label>
              <div class="radio radio-no-margin">
                <%= f.input :orientation, label: false, as: :radio_buttons, collection: [['<strong>Horizontal</strong>'.html_safe, 'landscape'],['<strong>Vertical</strong>'.html_safe, 'portrait']], :selected => 0 %>
              </div> <!-- /radio -->
              <div class="help-block help-block-brand">
                <%= t 'editor.create_new_story_form.end_notification'%>
              </div>
            </div>
          </div>

          <div class="row row-gutter">
            <div class="col-sm-4">
              <div class="btn btn-link btn-link-underline" onclick="discard_draft(event);">
              <%= t 'dashboard.cancel'%></div>
            </div>
            <div class="form-disabled">
              <div class="col-sm-8 text-right create_edit_img">
                <% unless @story.story_pages[0].illustration %>
                  <span class="gutter-sm-x vertical-i-top spacing-half-v">
                    <%= f.button :submit, "#{t 'editor.create_new_story_form.start_with_images'}" , data: {disable_with: "Creating..."}, :class => "btn-app btn-brand-1" %>
                  </span>
                  <span class="gutter-sm-x vertical-i-top spacing-half-v">
                    <%= f.button :submit, "#{t 'editor.create_new_story_form.start_with_words'}" , data: {disable_with: "Creating..."}, :class => "btn-app btn-brand-1" %>
                  </span>
                <% else %>
                  <span class="gutter-sm-x vertical-i-top spacing-half-v">
                    <%= f.button :submit, "#{t 'editor.create_new_story_form.start'}" , data: {disable_with: "Creating..."}, :class => "btn-app btn-brand-1" %>
                  </span>
                <% end %>
              </div>
            </div>
          </div>
        </div> <!-- /modal-body -->
      </div> <!-- /modal-content -->
    <% end %>
  </div> <!-- /modal-dialog -->
</div> <!-- /modal -->

<script type="application/javascript">
  // Enabling varnam when the form already has langauge selected.
  // (Ex: When page reloads after validation error)
  $(document).ready( function(){
    var languageId = document.getElementById("story_language_id").value;
    if (languageId != ""){
      select_language();
    }
  });

  $("#new_story").submit(function(){$.blockUI();});
  if (document.getElementById("story_language_id").value == "") {
    $(".form-disabled").addClass("disabled");
    $(".form-disabled").css('pointer-events', 'none');
    $(".form-disabled").find("input").attr("tabindex", "-1");
  }
  function select_language(){
    var language_id = document.getElementById("story_language_id").value;
    var language_name = $("#story_language_id option:selected").text();
    var story_field_classes = document.getElementById("story_title").className
    var story_class = 'string required form-control input-brand input-brand--lg english';
    if(story_field_classes != story_class){
       $("#story_title").removeClass(story_field_classes)
       $("#story_title").addClass(story_class)
    }
    add_language_script(language_id)
    $("#story_title").off("keyup");
    $("#story_title").off("keydown");
    if (language_id != "") {
      $(".form-disabled").removeClass("disabled");
      $(".form-disabled").css('pointer-events', 'auto');
      $(".form-disabled").find("input").removeAttr("tabindex");
      var varnam = new VarnamIME($("#story_title")[0], null, {name: language_name}, '<%= Settings.varnam.url %>').init();
    }else{
      $(".form-disabled").addClass("disabled");
      $(".form-disabled").css('pointer-events', 'none');
      $(".form-disabled").find("input").attr("tabindex", "-1");
    }
  }

  function add_language_script(language_id){
    $.ajax({
      url : '/v0/editor/language_script',
      type: "GET",
      data : {lang_id: language_id},
      contentType: false,
      dataType : 'json',
      success: function(data){
        $("#story_title").addClass(data['language_script'])
      }
    });
  }
  function discard_draft(e){
    e.preventDefault();
    window.onbeforeunload = false;
    $.ajax({
            type: "delete",
            url: "<%= delete_draft_story_path(@story) %>",
            dataType: "script"
           });
  }

</script>

app/views/stories/_translated_story_review_form.html.erb
<%= simple_form_for @reviewer_comment, :url => @reviewer_comment.id == nil ? reviewer_comments_path : save_review_edit_form_path(:reviewer_comment_id => @reviewer_comment.id), :method => :post, :remote => true do |f| %>
		<div class="story_review_form">
			<b><label>1. What did you think of the translation? Please refer to the original story before you share your thoughts.</label></b>
			<div class="review_options"><%=f.input :story_rating,:collection =>  ReviewerComment.story_ratings.collect {|key,value| [key,value] }.compact,:as => :radio_buttons, :label => false, input_html: {required: true }, checked: ReviewerComment.story_ratings[f.object.story_rating] %></div>
		</div>
		<div class="story_review_form">
			<b><label>2. What do you think of the language used in the story?</label></b>
			<div class="review_options"><%=f.input :language_rating,:collection => ReviewerComment.language_ratings.collect {|key,value| [key,value] }.compact,:as => :radio_buttons,:label => false, input_html: {required: true }, checked: ReviewerComment.language_ratings[f.object.language_rating]%></div>
		</div>	
		<div class="story_review_form">
			<b><label>3. How would you rate this story?</label></b>
			<div class="review_options"><%= f.input :rating,:label => false,:input_html => { class: "rating star_reset", "data-size" => 'xs'} %></div>
		</div>
		<div class="story_review_form">
			<b><label>4. Do you have something more you want to tell us about the story? Write here. (Optional)</label></b>
			<div class="review_options"><%= f.input :comments,:label => false,:input_html => { style: "width: 50%"} %></div>
		</div>
		<div class="story_review_form">
			<%= f.submit "Submit", class: "btn btn-normal btn-warning review_options submit_rating" %>
		</div>
<% end %>
<div id="trishold_model" title="Oops!" class="modal">There seems to be a mismatch in your responses. Would you like to have a re-look at your review form?</div>
<script>
$(".submit_rating").click(function(e){
	var story_rating =$('input[name="reviewer_comment[story_rating]"]:checked').val() 
	var language_rating = $('input[name="reviewer_comment[language_rating]"]:checked').val()
	var star_rating = $('#reviewer_comment_rating').val()
	if(((story_rating < 3 && language_rating < 3) && star_rating > 3) || ((story_rating > 3 && language_rating > 3) && star_rating < 3)) {
		e.preventDefault()
		$('#trishold_model').dialog({
		    autoOpen: true,
		    width: 400,
		    modal: true,
		    buttons : {
		      "Yes" : function() {
				    	$('#trishold_model').dialog('close');
		          e.preventDefault();
		        },
	        "No" : function(){
	          $('#trishold_model').dialog('close'); 
			    	$(".submit_rating").submit()
	        }
		    },
		    dialogClass: 'change_orientation_dialog'
			});
	}
});

$(document).ready(function() {
	$("#flag_form").on('click', function() {
		$("body").addClass("modal-open");
	});	
});
</script>

app/views/stories/create.js.erb
setTimeout($.unblockUI, 1);
window.location.href = "<%= story_editor_path(@story) %>";

app/views/stories/edit_story_editor.js.erb
$("#assign_change_editor").html("<%=escape_javascript(render(:partial=>"editor_form")) %>");

$("#story_editor_id").autocomplete({
        source: function( request, response ) {
        $.ajax({
          url: "<%= users_autocomplete_path%>",
          dataType: "json",
          data: {
           query: request.term
          },
          success: function( data ) {
            response(data);
          }
        });
      }
    });

app/views/stories/flag_story.js.erb
if("<%=@path %>" == "reviewer_path"){
	window.location = "<%= reviewer_un_reviewed_stories_path %>"
}else{
	window.location.reload();
}